### ISSUE TITLE
Message received acknowledge

### ISSUE THREAD

**Issue by MuallimCh** [LonamiWebs/Telethon#1]
I successfully try interactive_telegram_client, but I noted that client never send acknowledge for read status (double check sign).

How do I achieve that ?.

**Comment by XyLoNaMiyX** [comment]
I'm not aware whether there's a specific request for that. Maybe you need to read the message history and Telegram itself updates the read status. However, all the requests are available, and this is not related Telethon itself, but rather to how to use the requests. Closing issue. Thanks for your interest.

**Comment by MuallimCh** [comment]
I think you close this issue too early, while I did invoke ReadHistoryRequest after updatehandler(); but it seem returns nothing or unresponsive.

**Comment by XyLoNaMiyX** [comment]
I closed the issue because Telethon is simply an implementation of Telegram's API, not a full featured client, hence it's missing some features which it probably won't include. It's up to the users to use the library as they wish (and for them to implement the missing features, in the way they want).

`GetHistoryRequest` "returning nothing" or "unresponsive" is another issue unrelated to "not sending read status".

Anyway, I think I found what you needed. Please have a look at [these lines on the `scheme.tl`](https://github.com/LonamiWebs/Telethon/blob/master/scheme.tl#L372-L373) and try them out.

**Comment by XyLoNaMiyX** [comment]
By the way, if you implement the `send_read_acknowledge` method under the `TelegramClient` in a way which is both easy to use and user friendly, please feel free to make a pull request, I would appreciate! But as of now, I have more important plans which I think have an higher priority in the road map :)

**Comment by MuallimCh** [comment]
I just found solution to mark double tick, the invoke ReadHistoryRequest must be called outside add_update_handler(), since it was an event.

I think this is a note, for next update interactive_telegram_client.py

**Comment by XyLoNaMiyX** [comment]
Alright, thanks for testing! (I noticed that [these](https://github.com/LonamiWebs/Telethon/blob/15994d0b7822346c46e0ba1734ef16e015168816/scheme.tl#L372-L373) are _types_, not _functions_ 😳)

But what do you mean by _outside_? Requests can also be invoked inside the `update_handler` (beware of infinite loops, for example if automatically replying to a bot which also replies right away!)

**Comment by XyLoNaMiyX** [comment]
@MuallimCh I have more questions about this. Do we consider this fixed since you found a way? Should another easier method (more easily recognizable such as, for example, "send messages read acknowledge") be implemented? If so, how? Do you have any ideas?

**Comment by MuallimCh** [comment]
I am sorry for late reply. Yes indeed we can acknowledge message by invoke ReadHistoryRequest.
Implementing it, I think its pretty easy.

**Comment by XyLoNaMiyX** [comment]
I wonder if there is any other simpler way. We don't really want to read the history request, all we need is to tell Telegram that we've received the messages and read them.

There's a type, which is also used as request called `MsgsAck`. But that only works for telling Telegram that we received a packet, not a message (AFAIK). So I don't really know if implementing it as reading history request, because that involves transferring unnecessary bytes over the network.

**Comment by MuallimCh** [comment]
Nope, ReadHistoryRequest just return single line. Like below:

(messages.affectedMessages (ID: 0x84d19185) = (pts=1042, pts_count=0))

**Comment by XyLoNaMiyX** [comment]
Do you know what the `ReadMessageContentsRequest` does? I wish Telegram had a better documentation... I don't know what `pts` means either 😓

**Comment by XyLoNaMiyX** [comment]
Oh! My bad, `ReadHistoryRequest` and `GetHistoryRequest` are actually two different things lol. Let's try some stuff out.

**Comment by XyLoNaMiyX** [comment]
Okay, that was so silly. I only had to add _two_ lines, literally. Any idea on how to call the method? Here are some:
- `send_messages_read_acknowledge`
- `send_msgs_read_ack`
- `notify_messages_read`
- `notify_history_read`
- `notify_messages_received`

I don't know which one I like better.

**Comment by MuallimCh** [comment]
The first is better ..
Implement it under command **!h** from interactive_telegram_client.py

For now .. I am busy on find out how to retrieve or create a **InputPeerUser** type based on telegram id. Any Idea ?

**Comment by XyLoNaMiyX** [comment]
> The first is better

Sadly, it also is very long. I don't know about you, but I find it tedious to write long function names ;)

> Implement it under command `!h`

Reading (getting) the history as usual doesn't update the read status? It should! I can't try that quite now, but it should.

> I am busy on find out how to retrieve or create a InputPeerUser type based on telegram id

Why would you need to do that? There are methods to retrieve `InputPeerUser`'s, no need to hand-craft them. Without going any further, `get_dialogs` already returns a list of those. I think you cannot create them by hand with just their Telegram `id`, because you also need their `access_hash` (or, at least, that's what `InputPeerUser`'s contain). If you could, it would kind of be a security flaw!

**Comment by MuallimCh** [comment]
> Sadly, it also is very long. I don't know about you, but I find it tedious to write long function names ;)
To be readable and under kind function **send_message** may be send_message_read_ack

> Reading (getting) the history as usual doesn't update the read status? It should! I can't try that quite now, but it should.
Nope

**Comment by XyLoNaMiyX** [comment]
> To be readable and under kind function `send_message` may be `send_message_read_ack`

If I were a new user using Telethon for the first time, I wouldn't understand what "read ack" meant.

> Nope

That's really weird. Maybe we should just add a parameter `send_read_acknowledge=False`.

Anyway, now that you know "how to retrieve or create a `InputPeerUser`", are you up to implement this? I'd love to see more contributors (as in me not being the only one writing the code).

**Comment by XyLoNaMiyX** [comment]
After you've tested it @MuallimCh we can close the issue (I can't try it now 😓)

**Comment by XyLoNaMiyX** [comment]
Thanks :)
