### ISSUE TITLE
system clock offset causes client crash

### ISSUE THREAD

**Issue by TheRealNoob** [LonamiWebs/Telethon#1011]
OS: Windows 10
Package: Telethon

Problem:  By all appearances one of my two clients running in a single file.py crashed and doesn't restart.  I know that the other client is still working because it's still sending messages.  Not sure why one client would crash because of this issue and the other not, but it's still something to go on.

logs:
https://gist.github.com/TheRealNoob/074d75ac930c73a666247c27696b202e

These are not the entirety of the logs, this is just the parts that i felt were most relevant.  The logs continue after the error message at the end, which I assume is when two_client died, so all logs henceforth are from the still live client (one_client).

According to the chat that I had these running in, two_client stopped at 10:50 or 10:51.  The first error message appears in line 1309.

**Comment by Lonami** [comment]
Sadly git fast-forwarded the changes instead of creating a merge commit. Either way, the range https://github.com/LonamiWebs/Telethon/compare/096424ea7809e5512a932c79eff6676695c1d27e...dc7713645329c26b83c38fa0350a69031d81c638 may have fixed this, so I'm closing the issue. Please test master and reopen if it still happens after.
