### ISSUE TITLE
offset_date in  iter_dialogs and iter_messages is not working

### ISSUE THREAD

**Issue by dirkwirth** [LonamiWebs/Telethon#1043]
Hey folks,
First of all, thank you very much on your contribute.
Second, i tried to execute this code:

```python
import datetime

dialogs = client.iter_dialogs(offset_date=datetime.datetime.today() + datetime.timedelta(days=-1))
async for dialog in dialogs:
    print("Chat: ", dialog.name)
```

The output:
```
Chat:  Test1-Good User Time: 2018-10-08 08:58:37+00:00
Chat:  Test2-Bad User Time: 2018-09-13 11:00:12+00:00
Chat:  Test3-Good Chat Time: 2018-08-20 13:51:36+00:00
Chat:  Test4-Bad Chat Time: 2018-08-20 13:51:13+00:00
Chat:  Test5-Good Channel Time: 2018-08-20 12:11:14+00:00
Chat:  Test6-Bad Channel Time: 2018-05-08 19:13:04+00:00
Chat:  Testttttt Time: 2018-06-21 10:42:53+00:00
Chat:  Testttttt1234 Time: 2018-05-08 19:13:04+00:00
```

You can see this is not working. i would like if you can help me :)

Thank you very much!

**Comment by Lonami** [comment]
It's possible Telegram is just ignoring the date. The library uses all offsets because some alone just don't work. I encourage you to call [`GetDialogsRequest`](https://lonamiwebs.github.io/Telethon/methods/messages/get_dialogs.html) manually with the offsets you want, and see for yourself.

One way or another, the library could have a client-side check to avoid this, if the API doesn't work right.

**Comment by Lonami** [comment]
That's funny enough:
```python
for d in client.iter_dialogs(3):
    print(d.date)
print('vs.')
for d in client.iter_dialogs(3, offset_date=datetime.datetime.now() + datetime.timedelta(days=1)):
    print(d.date)
```

Output:
```
2019-01-03 10:23:19+00:00
2019-01-03 21:11:50+00:00
2019-01-03 21:10:38+00:00
vs.
2019-01-03 21:11:50+00:00
2019-01-03 21:10:38+00:00
2019-01-03 21:10:02+00:00
```

Looks like Telegram completely ignores this!

**Comment by LordST95** [comment]
I guess that's because of you set initial data on the definition of iter_dialogs() like :
`
offset_date = None,
offset_id = 0,
offset_peer = types.InputPeerEmpty()
`
when the developer normally use sth like `client.get_dialogs(limit=5,offset_id=6)`, the other parameters set to what you defined on the definition of get_dialogs and that's the why telegram's api, doesn't understand it. and if dev sets all parameters related to offset, like this:
`
client.get_dialogs(
        offset_date=datetime.datetime(2019, 8, 30),
        offset_id=6,
        offset_peer=lastPeer,
        limit=5,
    )
`
everything just work fine.
