### ISSUE TITLE
How to get Seconds in FloodWaitError ?

### ISSUE THREAD

**Issue by SleepyLotus** [LonamiWebs/Telethon#1114]
Hi
i'm trying to check some chat links and when i get the FloodWaitError know how much time i have to wait before request again.

in the documentation it mentioned that you can get the wait time , but i couldn't figure out how , and i couldn't find it anywhere else:
FloodWaitError (420), the same request was repeated many times. Must wait .seconds (you can access this parameter).
[https://telethon.readthedocs.io/en/latest/extra/troubleshooting/rpc-errors.html](url)

this is some part of code:

     from telethon.errors import InviteHashExpiredError, FloodWaitError

        try:

            try:

                check = await client_temp1(CheckChatInviteRequest(gp_list[chat_pointer]))

                print(check)

            except InviteHashExpiredError:

                print('Expired')

            chat_pointer += 1

        except FloodWaitError:

            print(FloodWaitError.message)

            await asyncio.sleep(10)

**Comment by Lonami** [comment]
You literally pasted the right part of the documentation in the issue (although it's misleading since it's an attribute, not a parameter). This is a question though, and doesn't belong here. The [issue template](https://github.com/LonamiWebs/Telethon/blob/master/.github/ISSUE_TEMPLATE.md) points you to the right place.
