### ISSUE TITLE
Infinite reconnect loop when connecting to mtproto proxy closes connection

### ISSUE THREAD

**Issue by seriyps** [LonamiWebs/Telethon#1134]
When making an attempt to connect to telegram via MTProto proxy using protocol that proxy doesn't support (eg, trying to connect via `Abridged`, when proxy only allows `RandomizedIntermediate`), or when trying to connect with wrong secret, proxy will close connection immediately after it receives 1st 64byte header. This causes infinite reconnect loop in `telethon.mtprotosender` (because connection is opened and then quickly closed):

```
INFO:telethon.crypto.aes:libssl detected, it will be used for encryption
INFO:mtp_monitor.management.commands.mtp_check:checking 159.69.150.89:443 4eeb5f61bcf8c1717a75b06e6120beef
DEBUG:asyncio:Using selector: EpollSelector
INFO:telethon.network.mtprotosender:Connecting to 159.69.150.89:443/TcpMTProxyIntermediate...
INFO:telethon.network.mtprotosender:Connection to 159.69.150.89:443/TcpMTProxyIntermediate complete!
INFO:telethon.network.connection.connection:The server closed the connection
INFO:telethon.network.mtprotosender:Connection closed while receiving data
INFO:telethon.network.mtprotosender:Connecting to 159.69.150.89:443/TcpMTProxyIntermediate...
INFO:telethon.network.mtprotosender:Connection to 159.69.150.89:443/TcpMTProxyIntermediate complete!
INFO:telethon.client.updates:Asking for the current state after reconnect...
INFO:telethon.network.connection.connection:The server closed the connection
INFO:telethon.network.mtprotosender:Connection closed while receiving data
INFO:telethon.network.mtprotosender:Connecting to 159.69.150.89:443/TcpMTProxyIntermediate...
INFO:telethon.network.mtprotosender:Connection to 159.69.150.89:443/TcpMTProxyIntermediate complete!
INFO:telethon.client.updates:Asking for the current state after reconnect...
INFO:telethon.network.connection.connection:The server closed the connection
INFO:telethon.network.mtprotosender:Connection closed while receiving data
INFO:telethon.network.mtprotosender:Connecting to 159.69.150.89:443/TcpMTProxyIntermediate...
INFO:telethon.network.mtprotosender:Connection to 159.69.150.89:443/TcpMTProxyIntermediate complete!
INFO:telethon.client.updates:Asking for the current state after reconnect...
INFO:telethon.network.connection.connection:The server closed the connection
INFO:telethon.network.mtprotosender:Connection closed while receiving data
INFO:telethon.network.mtprotosender:Connecting to 159.69.150.89:443/TcpMTProxyIntermediate...
INFO:telethon.network.mtprotosender:Connection to 159.69.150.89:443/TcpMTProxyIntermediate complete!
INFO:telethon.client.updates:Asking for the current state after reconnect...
INFO:telethon.network.connection.connection:The server closed the connection
INFO:telethon.network.mtprotosender:Connection closed while receiving data
```

Expected behaviour:

Telethon should stop making reconnection attempts after `connection_retries` attempts.

**Comment by Lonami** [comment]
The problem with this is that the connection is correctly estabilished within `connection_retries`:
https://github.com/LonamiWebs/Telethon/blob/a5f5d6ef235409f9757eef4dbc39d210af59d5a2/telethon/network/mtprotosender.py#L214-L227

Yet, the disconnection occurs immediately after (probably after attempting to send or receive data?).

I can think of a few solutions:
* `connection_retries` is per-instance. If a disconnection occurs at any moment, or a connection attempt fails, the remaining retries decrease. This is bad because the limit will be reached eventually (Telegram sometimes closes the connection under normal operation).
* `connection_retries` has a timeout before it's reset (so they may decrease within, say, 5 seconds). This is bad because we have to hardcode a number (and even as a parameter it would be more noise and a bit of a guess) and the network may just be bad and need more than whatever number we put. Or perhaps the device is slow and needs that long.
* Somehow check whether the connection was closed right after connecting. Perhaps sending a ping is required, perhaps selecting the connection is enough. Problems, this forces us to unconditionally send the ping, or `asyncio.open_connection` may not even support checking if it was closed (would need some investigation).

Do you have the code and proxy that triggers this issue at hand?

**Comment by seriyps** [comment]
The code is quite "classical":

```
proxy = (host, port, secret)
protocol = ConnectionTcpMTProxyAbridged
client = TelegramClient(
        "telethon-session",
        settings.MTP_CHECK_API_ID,
        settings.MTP_CHECK_API_HASH,
        connection = protocol,
        connection_retries = 0,
        request_retries = 1,
        auto_reconnect = False,
        timeout = timeout,
        proxy = proxy)
client.start(phone = settings.MTP_CHECK_PHONE,
                     password = settings.MTP_CHECK_PASSWORD)
me = client.get_me()
```

And about proxy... well... it seems not all of them close connection when there is a connection with unsupported protocol or wrong secret... I can post one, but it's not a fact that it will be available for a long time - they tend to "disappear" after some time, when spotted by censors.
Can try with this one
https://t.me/proxy?server=194.1.238.197&port=443&secret=ddddb75ddccaf9c7fdf2bfdfca20ddbeef

**Comment by Lonami** [comment]
Calling `self._reader.at_eof()` immediately after draining the writer (for flushing `_init_conn()`'s result) returns `False`. However, if you attempt to `read(n)` with `n > 0`, and then call it again, it's `True` (you can also notice this because the read returns `b''`). Attempting to `read(0)` will sadly not do anything, so we can't use that to our advantage. I don't know if we can check `at_eof()` differently.

If not, we could attempt to read 1 byte and remember it before the next read call, perhaps with a custom object (so it first returns that one byte, then the rest, and finally we can replace our dummy reader with the original).

**Comment by seriyps** [comment]
Thanks!
