### ISSUE TITLE
Getting inputUser without access_hash

### ISSUE THREAD

**Issue by feodoran** [LonamiWebs/Telethon#114]
The [Telegram API documents  a way](https://core.telegram.org/type/InputUser) to get a user from your contact list by `user_id` but without `access_hash`.

As I could not find this call in Telethon, I added the following to `scheme.tl`,
```
inputUserContact#86e94f65 user_id:int = InputUser;
inputUserForeign#655e74ff user_id:int access_hash:long = InputUser;
```
executed `tl_generator.py` and tested it with
```
InputUser = client.invoke(telethon.tl.types.InputUserContact(user_id))
```
where `user_id` should correspond to someone from your contact list.

And I get the following Traceback:

```
  File "test.py", line 47, in <module>
    InputUser = client.invoke(telethon.tl.types.InputUserContact(user_id))
  File "/path/to//telethon/telegram_client.py", line 224, in invoke
    request, timeout=timeout, updates=updates)
  File "/path/to//telethon/telegram_bare_client.py", line 189, in invoke
    self.sender.receive(request, timeout, updates=updates)
  File "/path/to//telethon/network/mtproto_sender.py", line 105, in receive
    remote_msg_id, remote_seq, reader, updates)
  File "/path/to//telethon/network/mtproto_sender.py", line 209, in _process_msg
    return self._handle_container(msg_id, sequence, reader, updates)
  File "/path/to//telethon/network/mtproto_sender.py", line 281, in _handle_container
    inner_msg_id, sequence, reader, updates):
  File "/path/to//telethon/network/mtproto_sender.py", line 218, in _process_msg
    return self._handle_bad_msg_notification(msg_id, sequence, reader)
  File "/path/to//telethon/network/mtproto_sender.py", line 321, in _handle_bad_msg_notification
    raise error
telethon.errors.rpc_errors.BadMessageError: (BadMessageError(...), 'Odd msg_seqno expected (relevant message), but even received.')
```
A similar call with `messages.GetChatsRequest()` works fine. So I assume there is something wrong with `InputUserContact`. Any ideas?

**Comment by Lonami** [comment]
> ```python
> InputUser = client.invoke(telethon.tl.types.InputUserContact(user_id))
> ```

`telethon.tl.types`. [Quote](https://lonamiwebs.github.io/Telethon/):
> Methods, also known as *requests*, are used to interact with the Telegram API itself and are invoked with a call to `.invoke()`. **Only these** can be passed to `.invoke()`! You cannot `.invoke()` types or constructors, only requests. […]

I've asked several people about what do they expect when they try to invoke a "type" but I'm yet to have a clear answer, sigh.

Regarding your problem, you can't just make up a new type like that. [The scheme is just the way it is](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/Resources/scheme.tl), and it's what's running in the server. If you made up a new type, the server would not be able to recognize it, and fail in a different way.

> The [Telegram API documents  a way](https://core.telegram.org/type/InputUser) […]

You are aware that the latest layer available there is 23, and Telethon is running layer 66! The official documentation is highly outdated, on respect to the available requests and types.

Finally, if they're your [contacts](https://lonamiwebs.github.io/Telethon/constructors/input_phone_contact.html) you can probably use [`ImportContactsRequest`](https://lonamiwebs.github.io/Telethon/methods/contacts/import_contacts.html) to work with it. You may also want to cache the `access_hash` yourself somewhere so that you don't need to query that every time, if all you know is the `id`.

**Comment by feodoran** [comment]
> You are aware that the latest layer available there is 23, and Telethon is running layer 66! The official documentation is highly outdated, on respect to the available requests and types.

No actually I thought the official documentation would be up to date. Thank you for clearing this up.

> Finally, if they're your contacts you can probably use ImportContactsRequest to work with it. You may also want to cache the access_hash yourself somewhere so that you don't need to query that every time, if all you know is the id.

Did you maybe mean [`GetContactsRequest`](https://lonamiwebs.github.io/Telethon/methods/contacts/get_contacts.html) ? `ImportContactsRequest` seem to be about uploading a Contact to the server.

Now, what can I do with the `Contact` type? How do I get a User?

Or to ask in a different way: To start a [`new chat`](https://lonamiwebs.github.io/Telethon/methods/messages/create_chat.html) I need `InputUser`, can I get this from `Contact`?

**Comment by Lonami** [comment]
> Did you maybe mean [`GetContactsRequest`](https://lonamiwebs.github.io/Telethon/methods/contacts/get_contacts.html) 

Yes sorry.

> Now, what can I do with the Contact type? How do I get a User?

You retrieve [`Contacts`](https://lonamiwebs.github.io/Telethon/constructors/contacts/contacts.html), which consists on a vector of contacts and a vector of users. There are your users.

**Comment by feodoran** [comment]
Ah, now I see it. Thank you!
