### ISSUE TITLE
i can not use Telethon in windows

### ISSUE THREAD

**Issue by arta66** [LonamiWebs/Telethon#115]
i install Telethon with pip3 in my windows but when i import Telethon in idle(python Gui) is have erore
`
C:\Users\arta>pip3 install telethon
Downloading/unpacking telethon
Downloading/unpacking pyaes (from telethon)
  Downloading pyaes-1.6.0.tar.gz
  Running setup.py (path:C:\Users\arta\AppData\Local\Temp\pip_build_arta\pyaes\setup.py) egg_info for package pyaes
Installing collected packages: telethon, pyaes
  Running setup.py install for pyaes
Successfully installed telethon pyaes
Cleaning up...
``

`from telethon import TelegramClient`
`Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from telethon import TelegramClient
  File "C:\Python34\lib\site-packages\telethon\__init__.py", line 3, in <module>
    from .interactive_telegram_client import InteractiveTelegramClient
  File "C:\Python34\lib\site-packages\telethon\interactive_telegram_client.py", line 10, in <module>
    cols, rows = shutil.get_terminal_size()
  File "C:\Python34\lib\shutil.py", line 1057, in get_terminal_size
    size = os.get_terminal_size(sys.__stdout__.fileno())
AttributeError: 'NoneType' object has no attribute 'fileno'`

**Comment by moasakthi** [comment]
FYI, the size of the terminal associated with the C's stdout isn't related to the IDLE shell. For example, in Linux when I run IDLE from the GUI, the associated terminal size is 0x0. 

On Windows, os.get_terminal_size uses the console API GetConsoleScreenBufferInfo. This can't work given IDLE has no attached console. Also, for a GUI app the Windows C runtime leaves the standard FILE streams uninitialized to an invalid file descriptor (-1), so Python's sys.__stdout__ is None. That's why you get an AttributeError complaining that NoneType (i.e. type(None)) has no attribute 'fileno'.

Currently shutil.get_terminal_size returns the fallback size when os.get_terminal_size(sys.__stdout__.fileno()) raises NameError or OSError. I think AttributeError and ValueError should be added to this list

**Comment by Lonami** [comment]
> so Python's sys.stdout is None. That's why you get an AttributeError complaining that NoneType (i.e. type(None)) has no attribute 'fileno'.

Thank you for the help @moasakthi. As he said, @arta66, that's the issue. Anyway, the `InteractiveTelegramClient` will stop being shipped on the next release, so I will close the issue. You'll have to wait for the next release, which should be soon.
