### ISSUE TITLE
iter_participants doesn't return all the participants

### ISSUE THREAD

**Issue by MrDarkest** [LonamiWebs/Telethon#1174]
Hi,
I'm trying to get the participants list from a channel where I'm admin.
I wrote this code for this purpose:

```python
import os
import sys
import time

from telethon import TelegramClient, events, sync

api_id = 123456
api_hash = 'telegram_api_hash'
#bot id of the channel
channel = -000000000000

client = TelegramClient('session_name', api_id, api_hash)
client.start()
# get all the channels that I can access
channels = {d.id: d.entity
            for d in client.get_dialogs()
            if d.is_channel}

# choose the one that I want list users from
channel = channels[channel]

# get all the users and print them
count = 0
for u in client.iter_participants(channel, aggressive=True):
  print(u.id, u.first_name, u.last_name, u.username)
  count+=1
print(count)
#disconnect client
client.disconnect()
```

The issue is that I've received only 1977 participants out of 2636
![issue](https://user-images.githubusercontent.com/20922157/57538672-388bbe80-7349-11e9-9dbf-2fe74b6bad8b.png)

**Comment by Lonami** [comment]
Server-side limitation. Not a bug.

**Comment by kuncevic** [comment]
interesting, trying the code above in my channel there is 61 people, but getting only 57

**Comment by zakaria47fs** [comment]
U may get all the participants by setting the 'agressive' parameter to False, since the participants number isn't greater than 10k

**Comment by serhiishtokal** [comment]
> U may get all the participants by setting the 'agressive' parameter to False, since the participants number isn't greater than 10k

@zakaria47fs thanks, it helped me to get the all participants

**Comment by alvindera97** [comment]
> U may get all the participants by setting the 'agressive' parameter to False, since the participants number isn't greater than 10k

@serhiishtokal , setting `agggressive=True` capped the number of returned participants to 200. Your comment doesn't mention that the `aggressive=True` argument would cause a cap to bet on the number of returned participants. Even if I had 9K participants, the method only returns 200 participants with `aggressive` set to `True`

**Comment by Mars2503** [comment]
In 2023 the iter_participants function with the aggressive = True / False doesn't work anymore.
I'm searching a new way to get a list with more than 200 members, but I think  that is no more possible do that.

**Comment by Lonami** [comment]
`aggressive` was bugged after some server-side changes so it no longer does anything: https://github.com/LonamiWebs/Telethon/commit/d7424ccb90123d03a3dbd2c8a2725c1bd01a40da

Telegram *really* doesn't want users to be able to fetch all participants, as this is very often used to spam. This limitation is done on the server-side. There is nothing Telethon can do to "fix" it. And I am not willing to try to implement more hacks such as `aggressive` (which was a hack) to try to work around those limitations. `iter_participants` works as intended.

I will be locking this conversation because there is not much more to say. To summarize:

**Telegram doesn't want users to fetch all participants, and this is not something Telethon can fix, because it's a server-side limitation.**
