### ISSUE TITLE
Message.text always None

### ISSUE THREAD

**Issue by fnkap** [LonamiWebs/Telethon#1238]
Hello.
Whenever I've got a Message, I can get

```
message.raw_text
message.message
```

just fine. However, if I try to get

`message.text`

it's always set to None, for every message. Tried version 1.8.0 and 1.9.0, same problem.

EDIT: This happens when I retrieve my Message object from GetHistoryRequest.
Instead, when I retrieve my Message object using client.iter_messages(), the .text attribute it's not None, but acts strangely:
If I use default parse_mode, its value is equal to .message attribute, if I use parse_mode='html' only urls get parsed.
EDIT2: It works fully as intended with client.iter_messages(), I had an unrelated error.
But still, when using GetHistoryRequest, the .text attribute is None.

**Comment by Lonami** [comment]
Yes, raw requests (`GetHistoryRequest`) do not modify Telegram's result at all (and thus don't have a `client` to determine how the `text` should be interpreted). There are plans to change this behaviour, but since it would be a breaking change it needs to be in v2.0. You should not use raw methods unless you have a good reason, though.
