### ISSUE TITLE
cant get all dialogs with loop

### ISSUE THREAD

**Issue by unkn19wn** [LonamiWebs/Telethon#13]
Hi 
i need to get all my dialogs with client.get_dialogs()
i tried to get there but unfortunately i couldn't

my code is :

```python
entity = client.get_dialogs(count=1000,offset_id=0)
print(entity[1][0].id)
entities=list()
for i in range(5):
    for i in range(len(entity[1])):
        if entity[1][i].id not in entities:
            entities.append(entity[1][i].id)
    try:
        entity = client.get_dialogs(count=1000,offset_id=entity[1][-1].id)
        print(entity[1][0].id)
    except:
        print("None Result ...")

print(len(entities))

print('Dialogs loaded.')
```

but it give None in return for 2nd loop and after that
i get at most 102 dialogs

i have 600 active dialogs now
i`ll be thankful if you give me a sample code for that

**Comment by XyLoNaMiyX** [comment]
Alright first of all I'm closing this because it's not quite Telethon related :)

Second, Telegram won't give you `1000` dialogs. You could try some lower number such as `100` or `50` for the batch size.

Third, perhaps you prefer to use `offset_peer` instead `offset_id`. Telegram API hasn't had an update of their documentations for a long while, so I don't quite know what every method means, sorry.
