### ISSUE TITLE
send_code_request not sending sms message

### ISSUE THREAD

**Issue by dannizi25** [LonamiWebs/Telethon#1302]
Whenever I try to login to a new user for the first time:
send_code_request 

Doesn't send SMS but when I tried an older version it did send and everything went fine

**Comment by Lonami** [comment]
We can only `force_sms`:
https://github.com/LonamiWebs/Telethon/blob/b862f215c58f8a2f3a56680a3db4c3d4ef9c096a/telethon/client/auth.py#L496-L498

If we didn't previously receive a result telling us that we already sent a SMS:
https://github.com/LonamiWebs/Telethon/blob/b862f215c58f8a2f3a56680a3db4c3d4ef9c096a/telethon/client/auth.py#L478-L486

So if `force_sms` is not working, it's probably a server-side issue. You may use `SendCodeRequest` manually yourself to try to figure out how it works. Or perhaps you need to wait 2 (?) minutes before forcing to resend the code.

Closing since there isn't much I can do about it.
