### ISSUE TITLE
Async session backends

### ISSUE THREAD

**Issue by GamePad64** [LonamiWebs/Telethon#1366]
Hi! I am using Redis session backend, and it seems inappropriate to me to use synchronous session backends, that rely on IO operations.
Is there any way to create a new base Session class, that uses async functions (and, maybe, properties?) and subclass current Session class from it?

**Comment by Lonami** [comment]
There currently is no way to create asynchronous sessions. This was attempted before, but the changes were reverted because the library relies on the lack of asynchronous sessions in some cases (think `event.input_chat`, the session may have the access hash we need but an `async` property would be weird).

So, asynchronous sessions are desirable, but some extra changes are needed (perhaps having all ID → hash to memory?).

**Comment by parikls** [comment]
@Lonami any updates regarding this? Without this particular feature - using multiple telegram sessions leads to a performance issues and basically we lose all the benefits of asynchronous approach

**Comment by Lonami** [comment]
You can use memory sessions and choose how to synchronize them to disk / database in any way you want.
