### ISSUE TITLE
How to correctly use the iter_download functionality for multi connection downloads

### ISSUE THREAD

**Issue by RT4U** [LonamiWebs/Telethon#1372]
There's no proper example in the documentation which is giving me a big headache how to properly implement this functionality.

I've been trying to implement a multi threaded Telegram download client. For single downloads we can simply use the download_media functionality.

But telethon offers iter_download function, as per documenation it is used for streaming which also includes pausing and resuming functionality. We can use this to download a single file with multiple connections.

This is what I've scripted so far. No where to find any solid examples for multi connection download

```
async def multi_downloader(file, total_size, part, offset, part_size):

f = open('output.mkv.'+str(part), 'wb')
size = 0

global chunk_size
limit = 10485760#closestInteger(part_size / chunk_size, 10485760)
print(limit)
print(part)
async for chunk in client.iter_download(obj, offset = offset, limit = limit, chunk_size = chunk_size, request_size = chunk_size, file_size = total_size):
    f.write(chunk)
    f.flush()
    size += (len(chunk))
    if size >= (part_size):
        print("Part "+str(part)+" completed. "+str(part_size))
        break
f.close()
```
The thing is it always throws the invalid limit error, if I change the offset for seeking. If the offset is zero then everything is fine.

> telethon.errors.rpcerrorlist.LimitInvalidError: An invalid limit was provided. See https://core.telegram.org/api/files#downloading-files (caused by GetFileRequest)

**Comment by Lonami** [comment]
> multi threaded Telegram download client

Remember the library uses `asyncio`, and using threads per se will give you even more headaches unless you know what you're doing.

> We can use this to download a single file with multiple connections

No, the documentation neither says this nor implies it. It will still be done over the same connection. Using multiple connections would be a good improvement, but requires messing around with the internals and careful design.

> No where to find any solid examples for multi connection download

Because this is not implemented. Where in the documentation did you get this idea from? Maybe we should clarify there are no multiple connections?

> The thing is it always throws the invalid limit error

Did you read [the documentation for `iter_download`](https://docs.telethon.dev/en/latest/modules/client.html#telethon.client.downloads.DownloadMethods.iter_download)?:

> **limit (`int`, optional):**
> The limit for how many *chunks* will be yielded at most.

**Comment by RT4U** [comment]
Hi,

The thing is, that's what am trying to implement. Sorry for the poor wording.

Downloading a file with 4 or 5 iter_download in separate threads, to improve the download speed.

The main issue here is playing with the offset values. For now let's forget about multi connection downloads and simply focus on the offset and limit part.


The thing is, as shown on the above code, whenever I change the offset to a value more than zero, I get that Invalid Limit error. (Even when no Limits are specified or specified)

I am just trying to find a robust solution for file seeking by changing the offset. May be could you please help me on that?

**Comment by Lonami** [comment]
Closing because "how to use" is not an issue but a question. The issues section in GitHub is only to report bugs or enhancements in the library itself. If you have usage questions, you should ask those in [StackOverflow](https://stackoverflow.com/questions/ask?tags=telethon) or [the @TelethonChat group](https://t.me/TelethonChat).
