### ISSUE TITLE
The phone code entered invalid

### ISSUE THREAD

**Issue by JepsonHerts** [LonamiWebs/Telethon#1386]
Hi,
This is my code:
client=TelegramClient(sessione, api_id, api_hash)
	client.connect()
	phone=input("Number: ")
	client.send_code_request(phone)
	code = input('Sms: ')
	client.sign_up(code, first_name=input("Nome: "), last_name=input("Cognome: "))

When i put the Sms code, it gives me an error saying that it is invalid with the error .....telethon.errors.rpc_error_list.PhoneCodeInvalidError: The phone code entered was invalid

But if I change the code to:
	client=TelegramClient(sessione, api_id, api_hash)
	client.connect()
	phone=input("Inserisci numero: ")
	client.send_code_request(phone)
	code = input('Codice sms: ')
	client.start(phone)
IT WORKS but it create an user with no name and last name etc...

**Comment by Lonami** [comment]
The error comes from Telegram, [since Telethon never raises it manually](https://github.com/LonamiWebs/Telethon/search?q=PhoneCodeInvalidError&unscoped_q=PhoneCodeInvalidError). You can investigate what `start` is doing with a debugger and mimic that. In any case, [`start` also lets you set the `first_name`](https://docs.telethon.dev/en/latest/modules/client.html#telethon.client.auth.AuthMethods.start). Closing as nothing to do.

**Comment by JepsonHerts** [comment]
How can i debug?
