### ISSUE TITLE
Update docs with examples of progress_callback

### ISSUE THREAD

**Issue by Aeres-u99** [LonamiWebs/Telethon#1396]
I am trying to run my program which basically downloads media from a channel. 
The code snippet from quickstart section
```
if message.video:
▏   path = await message.download_media(progress_callback(total))
▏   print("Saved: ",path)
```
this helps me in downloading the file but does not displays the progress.
From referring to the docs I could find this, but I am unable to understand how to use the callback for the purpose. Kindly provide me with an explanation.
[download_media()](https://docs.telethon.dev/en/latest/modules/client.html#telethon.client.downloads.DownloadMethods)

**Comment by Lonami** [comment]
For the record, since [you left so promptly](https://t.me/LonamiWebs/10148)…
```
<kei> greetings 😅
<kei> @lonami I had created the progress bar related issue, can you provide me with the syntax for it so that I can roll in action and finish my small project? i just dont understand how to use the callback.
<lonami> preferable if you don't ping me for how to use the lib
<kei> yeah you are correct. I should better bang my head against wall than to ask for help or ask someone to write somewhat better documentation.
<lonami> my point is you can ask the group (here or @telethonchat) or even stackoverflow without the need to ping anyone
<lonami> and they left
<lonami> ah well
```

**Comment by Aeres-u99** [comment]
It would have been much easier for you to convery the way without making fusses about it. True it might be rtfm type of issue, agreed that it could be asked on stackoverflow (which happens to have older version of telethon's answer btw) and I would love to know why you have not told me about the @telethonchat upon asking you twice. Nevertheless, Apologies for bothering you and wasting your time.

**Comment by Lonami** [comment]
Issues are for either bug reports or enhancements, not asking for support on how to use the library directly. For that, there are groups, and the groups exist because I don't want people asking me directly the questions (or pinging me, for that matter).

If StackOverflow has outdated questions, leave a comment saying that it no longer works and it should be updated, or ask a new question "how to do foo in Telethon 1.11".

The group chat for specific Telethon questions can be found trying to create a new issue https://github.com/LonamiWebs/Telethon/issues/new/choose and following the " Find about updates and our Telegram groups" link. I also had no chance to mention the group because you left so hastily…

**Comment by Aeres-u99** [comment]
isn't it an enhancement to the documentation? Also, instead of pointing out do no ping me, you could have said ask in @foobar and do not ping me. Nevertheless, its fixed and thats all I needed anyways.
