### ISSUE TITLE
telethon.errors.rpcerrorlist.FloodWaitError while sending message to batch of phone numbers

### ISSUE THREAD

**Issue by umax** [LonamiWebs/Telethon#1401]
**Code that causes the issue**
```python
from telethon.sync import TelegramClient
with TelegramClient('anon', API_ID, API_HASH) as client:
    for phone_number in phone_numbers:
        await client.send_message(phone_number, 'test message')
```

**Traceback**
```
functions.contacts.GetContactsRequest(0))).users:
  File "/Users/plastun/venv/telethon/lib/python3.7/site-packages/telethon/client/users.py", line 74, in __call__
    result = await future
telethon.errors.rpcerrorlist.FloodWaitError: A wait of 6991 seconds is required (caused by GetContactsRequest)
```

Is there any efficient way to send messages to my contacts?
I just want to send message to all my contacts.

**Comment by Lonami** [comment]
Working as intended, not a bug.

**Comment by umax** [comment]
Any suggestion or workaround how to send mass messages?

**Comment by edelvalle** [comment]
I click https://github.com/LonamiWebs/Telethon/issues?q=is%3Aissue++FloodWaitError

On every issue there is @Lonami being not very helpful at all.

This is not a problem of your library, but you will just get asked again and again about it. Instead of not being helpful, as for sure you have some more insight into this issue than we do. Could you point us to the right direction? Tell us where can we find a solution or report this problem, or why does it happen at all?

Because closing issues and just telling: "Working as intended, not a bug." and "Not the place to task" is not very or kind.

Anyway, thank you very much for this library! I know how much effort takes to make any open source project work and how much times it consumes, not just in development, but also answering questions about it and receiving complains.

Thanks!

**Comment by Lonami** [comment]
When you try to open an issue there are links taking you to places where you *can* ask questions. The GitHub bug tracker, issues section, is not for questions, and I have to draw the line somewhere. It's not about being kind or not. I will gladly help when people properly ask in the right places and I am willing to answer, but that's not going to happen here.

If you believe the documentation can be improved, open an issue suggesting to improve it (not asking for help!), or send a pull request.

If you want answers, ask in StackOverflow or the `@TelethonChat` group.

**Comment by edelvalle** [comment]
> If you want answers, ask in StackOverflow or the @TelethonChat group.

Thanks, that's actually helpful...!
