### ISSUE TITLE
events.MessageRead doesn't have any message in it

### ISSUE THREAD

**Issue by MehdiAghighi** [LonamiWebs/Telethon#1420]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
@client.on(events.MessageRead)
async def messageRead(event):
    if event.is_private:
        chat = await event.get_chat()
        messages = await event.get_messages()
        print(messages) # here
        await client.send_message("me", "[" + chat.username + "]" + "(" + "https://t.me/" + chat.username + ")" + " Has Read Your Message " + "👇")
```
in the code above where i am trying to print messages that are read, it tells me there are no messages and gives me below result when i am trying to print `messages`
```
[, total=0]
```

**Comment by thekillgfx** [comment]
I've tested `events.MessageRead ` too.

```
@events.register(events.MessageRead(func=lambda e: e.is_private))
async def messageRead(event):
    temp = await event.get_messages() #returns [, total=0]
    print(event.message_ids) #returns []
```

**Comment by Lonami** [comment]
The function states clearly that not all read messages are returned:

https://github.com/LonamiWebs/Telethon/blob/79fb1a54cb176993835ee0e83bb5af24722f8f7c/telethon/events/messageread.py#L106-L109

Telethon doesn't know what messages were read before this event, and as such it cannot say which messages were read by this event (because it could be any up to the maximum read ID). The API only returns particular IDs for those whose contents are read (i.e. when you play a voice note you listen to the contents so that would be fetched).

Closing as not actionable.
