### ISSUE TITLE
Add get_env helper from the examples to the main code

### ISSUE THREAD

**Issue by ov7a** [LonamiWebs/Telethon#1433]
[`get_env` function](https://github.com/LonamiWebs/Telethon/blob/master/telethon_examples/print_updates.py#L14) from telethon examples is a quite useful helper. I think it would be nice to add it to the main code.

First, it shows a clean way to get one's head around storing api secrets. It can easily be reused in simple scripts.

Second, the examples can be a bit cleaner without duplicate code.

**Comment by Lonami** [comment]
It's ten lines, and Telethon is a MTProto library. It should not aim to provide miscellaneous functions like that one.

The function is duplicated because I want the examples to be self-contained, and these are tiny examples that should not be used verbatim in the real world anyway (probably handle secrets properly, not via `stdin`).
