### ISSUE TITLE
Multiple Parallel Telegram Client uses one session

### ISSUE THREAD

**Issue by nnehdi** [LonamiWebs/Telethon#146]
HI
We want to run multiple TelegramClient Instance in multiple thread that work on only one session file. Because we want to skip signing in step for each instance.
But we get this session relevant error:
seq_num is too low...

There is a way we can have multiple TelegramClient with just one session and one sign in?
Can you explain about the session field store in the  session file like salt, auth_key_data, id and sequence and how this filed use by telethon?
tnx

**Comment by Lonami** [comment]
You're talking about [`create_new_connection`](https://github.com/LonamiWebs/Telethon/blob/c02fbae5aa311047a1973c4509b02069120c35ba/telethon/telegram_client.py#L195)?

**Comment by nnehdi** [comment]
But TelegramBareClient is an internal class that used by TelegramClient and do not support full feature like auto reconnection. Isn't it?
I'm a bit confused. Let's explain the full scenario that we want to use telethon.
we have a resful service that is writen by flask. and this service use telethon for fetching message and downloading media. this service is going to work on high scale, many many request per second.
we want to scale it up. thats why we sign in with over 100 user by telethon. 
we have running one instace of this servie that read and write session on one folder.
but we one to run multiple instance of this servie. 
and this is lead us to situation that mutiple instance of our service (TelegramClient)  read and write into one session So the sessions are corrupted.
any suggestion??

**Comment by Lonami** [comment]
> TelegramBareClient is an internal class

Not really, you're free to use it. Indeed, that method is public and returns a bare client for a reason. The reason is, the `TelegramClient` itself has way more things (such as handy methods like `.send_message()` etc.) which aren't needed for a "normal" use (a second connection doesn't need a thread for updates, or being able to create even more copies of itself).

You should always prefer a call to `.invoke()` to directly interact with the API rather than those I call "quick and dirty methods" for very common things. This is at least how I see it.

> thats why we sign in with over 100 user by telethon

Never tested Telethon under those circumstances, so I don't know how well it will work (there's a reason why it's not on `v1.0` just yet), but I'll be open to more issues, patches or suggestions if things go wrong.

> any suggestion??

Yes, using [`create_new_connection`](https://github.com/LonamiWebs/Telethon/blob/c02fbae5aa311047a1973c4509b02069120c35ba/telethon/telegram_client.py#L195). That will use the same session, the same file, and has internal `Lock`'s which (should) prevent "msg_seqno too low or high" errors.

> we use docker!

Never actually used that.

---

Now that we're talking about the distinction between `TelegramClient` and `TelegramBareClient`, I just wanted to clean-up the `TelegramClient` itself and remove some "useless" methods (such as sending a message, it's not so hard to `.invoke(SendMessageRequest(...))`), but a lot of people rely on them, and it really comes in handy.

Given that the `TelegramBareClient` is just the client itself, which comes in very handy for, say, creating another connection on a different data center and still be able to `.invoke()` requests to download media, I decided to make this clean(er) class, and use it instead creating a whole new `TelegramClient`. I hope that you can see my point.

Both the `TelegramClient` and `TelegramBareClient` are perfectly usable outside Telethon itself. Indeed, if you don't care about updates, you could go ahead and simply use a `TelegramBareClient`. I don't know how much memory would consume having all those methods and maybe a reconnection in the bare client.

Besides this, some bare clients are not meant to handle automatic reconnection, because they may have already been created when said reconnection is needed (only when downloading media from a different data center).

Also note that Telegram will *only* send updates to the *first* connection anyway, or that's the behaviour I came across with.

Sorry for the lengthy answer but I hope this clarifies the need for distinction and I'm open to new ideas.

**Comment by feodoran** [comment]
This is actually a follow up to https://github.com/LonamiWebs/Telethon/issues/148 (thanks for taking care of that), but it seems to be connected to this issue here.

So I can call now `create_new_connection()` and download files from varying DCs if I run this sequentially in one thread (which wouldn't actually require `client.create_new_connection()` in the first place).

But my use case now is similar to here: downloading the file in one (or more separate) background thread(s), and still being able to make other requests to Telegram. Basically what you want in an asynchronous application (continue chatting while downloading larger files). 
I tried this with `threading.Thread` and got `TimeoutError`. If I test with only 2 files, it works occasionally. With 3 files I get always the `TimeoutError`.

I guess this is connected to what you mentioned in https://github.com/LonamiWebs/Telethon/issues/148 but I could not follow you completely there.
If I get this correctly, you only use one socket (connection) for the session. So all client objects created with `create_new_connection()` have to share this (and use the thread lock), which might explain the timeouts. Would it be possible to export a session to a new client object with a separate socket? Something like `create_new_connection(new_socket=True)`
