### ISSUE TITLE
requesting sms

### ISSUE THREAD

**Issue by hnikaein** [LonamiWebs/Telethon#147]
Hi,
How I can request for sending an sms for authentication instead of sending message in telegram.
Excuse me for asking this, but I didn't find it in docs. 

thanks

**Comment by Lonami** [comment]
Should be done automatically. If the code isn't used within a certain period of time, Telegram should send an SMS.

**Comment by Lonami** [comment]
> Should be done automatically.

Yeah, it must be that.

**Comment by hnikaein** [comment]
didn't send :(

**Comment by Lonami** [comment]
> didn't send :(

That's strange, because I remember it being sent. Maybe you need not to be connected to any other Telegram application? Otherwise they may just send the code there. And I see [no request](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/Resources/scheme.tl) (or function) which explicitly allows setting SMS as desired type.

**Comment by hnikaein** [comment]
when you using telegram desktop, after it sends code to active telegram session, then it has a button named "send code via sms".

**Comment by Lonami** [comment]
[I guess it's this](https://github.com/telegramdesktop/tdesktop/blob/197cdc3928d2403814c147f8394ef42ed427c9d8/Telegram/SourceFiles/intro/introcode.cpp#L84), and [this](https://github.com/telegramdesktop/tdesktop/blob/197cdc3928d2403814c147f8394ef42ed427c9d8/Telegram/SourceFiles/intro/introcode.cpp#L96) event. What's done is that the [code is resent](https://github.com/telegramdesktop/tdesktop/blob/197cdc3928d2403814c147f8394ef42ed427c9d8/Telegram/SourceFiles/intro/introcode.cpp#L335). So it seems like [`ResendCodeRequest`](https://lonamiwebs.github.io/Telethon/methods/auth/resend_code.html) should do.

**Comment by hnikaein** [comment]
Correct.

**Comment by amir3code** [comment]
Well, Sorry for opening this issue again, but  https://core.telegram.org/method/auth.sendcode says about `SendCodeRequest` that `sms_type` is a parameter that if we send `5` to it it should send the confirmation message via telegram itself and not sms. Is it true? Why the implementation of core.telegram.org differs from the scheme.tl file?

**Comment by Lonami** [comment]
> Is it true?

It used to be true. Scheme changes. You can see all the versions [here](https://github.com/stek29/tl-schema).

> Why the implementation of core.telegram.org differs from the scheme.tl file?

Because they're outdated as heck. Do not rely on [core.telegram.org](https://core.telegram.org) documentation, unless you use Telethon with a layer as outdated as [23](https://core.telegram.org/schema). Things may not work, and you'd have to generate the code on your own. Not hard, just replace the `scheme.tl`, run the generator, and do some adjustments

The scheme [Telethon uses](https://lonamiwebs.github.io/Telethon/methods/auth/send_code.html) doesn't have the `sms_type` parameter, probably removed some time ago now. So, the process described here is the only way to request a SMS now it seems.

**Comment by Lonami** [comment]
As this is the original issue **which you should have searched for** @cdthy but yet doesn't have the code equivalent to Python, I'll just say it here again. What you must do is use [`ResendCodeRequest`](https://lonamiwebs.github.io/Telethon/methods/auth/resend_code.html)

**Comment by Lonami** [comment]
https://github.com/LonamiWebs/Telethon/commit/f381b267903cad2b7e208a5006a7cd10a02b6eb1

**Comment by Lonami** [comment]
Wrong button.

**Comment by Who-X1** [comment]
Any way to send code via sms if paid still i need it
