### ISSUE TITLE
min_date and max_date arguments are not working in SearchRequest function.

### ISSUE THREAD

**Issue by Morteza-Gh-Kh** [LonamiWebs/Telethon#1482]
I ran following code to get messages between two dates (`min_date`, `max_date`) but results shows that they both have no effects on results.

```
        result = await client(SearchRequest(
            peer=my_channel,
            q='',
            filter = InputMessagesFilterUrl(),
            min_date=datetime.datetime(2017, 11, 13),
            max_date=datetime.datetime(2019, 1, 9),
            offset_id=0,
            add_offset=0,
            limit=100,
            max_id=0,
            min_id=0,
            hash=0,
            from_id=None
        ))
        for message in result.messages:  
            print(message.date)
```

This is only a part of results that shows function isn't working properly:

```
2019-05-31 22:20:40+00:00
2019-03-01 08:13:49+00:00
2019-01-09 13:24:14+00:00
2018-10-28 09:11:24+00:00
2017-11-13 19:46:12+00:00
2017-10-23 09:46:34+00:00
2017-10-23 09:46:34+00:00
2017-10-23 09:45:53+00:00
```
As you can see, there is dates before and after that period of time specified in arguments.

**Comment by Lonami** [comment]
`client(request)` is what's known as "raw API", and Telethon has no control here. The results you see come directly from Telegram, and what you send goes directly to Telegram. If it's not working, it's because they also don't work in the Telegram API itself. Unfortunately, there's no way to fix this on the Telethon side.

I do know some offsets just don't work, not just with search if I remember correctly, and these non-working offsets are generally used in conjunction with other offsets. Perhaps that's their only purpose.
