### ISSUE TITLE
This is not a bug. but if you want to click a button you can use this simple code (i searched it for 1 hour and i find it)

### ISSUE THREAD

**Issue by furkan6116** [LonamiWebs/Telethon#1525]
sender = await event.get_sender()
messages = await client.get_messages(sender.username)
await messages[0].click(0)

This will click the first button in the message. You could also click(row, column), using some text such as click(text='👍') or even the data directly click(data=b'payload').

**Comment by Lonami** [comment]
For sharing things like this, you can answer your own question on StackOverflow or [add it to the wiki](https://github.com/LonamiWebs/Telethon/wiki), but I don't think it's really necessary since [a simple search is enough](https://docs.telethon.dev/en/latest/search.html?q=click&check_keywords=yes&area=default):

![image](https://user-images.githubusercontent.com/6297805/90394045-33600800-e092-11ea-9054-998988d24671.png)
