### ISSUE TITLE
Problem register new account

### ISSUE THREAD

**Issue by Soeyd** [LonamiWebs/Telethon#1543]
When trying to register, it always says that the code is not correct.

**Code that causes the issue**
```python
from telethon.sync import TelegramClient
...
phone = input('number: ')
client = TelegramClient(phone, API_ID, API_HASH)
client.connect()
code_hash = client.send_code_request(phone, force_sms=True)
code = input('code: ')
client.sign_up(code, 'Anna')
```

**Traceback**
```
 result = await future
telethon.errors.rpcerrorlist.PhoneCodeInvalidError: The phone code entered was invalid (caused by SignUpRequest)

```

**Comment by Lonami** [comment]
The code cannot be sent over Telegram or it will expire immediately. Some locations (aws) are also restricted. I encourge you to try to use raw API instead of the friendly client methods and see if the issue persists. If it does, it's a problem with Telegram, not the library. Closing as probably not actionable.
