### ISSUE TITLE
[security] reusing session with API ID / API Hash changes

### ISSUE THREAD

**Issue by shinenelson** [LonamiWebs/Telethon#1569]
I am not sure if this is a issue with telethon or Telegram itself. Changing the API ID or API hash parameter in the `TelegramClient()` does not trigger a re-authentication request if the local session sqlite3 database already exists.

### Checklist
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [ ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.
	* I am running a more recent version ( https://github.com/LonamiWebs/Telethon/commit/2c9d43d60027a0ae4bd37bb80cd5e1020b703cbc ) than the [latest release](https://github.com/LonamiWebs/Telethon/releases/latest) because I am running from source. However, the [2 commits](https://github.com/LonamiWebs/Telethon/compare/2c9d43d..master) since my version does not seem to address session handling so I didn't `pull` those commits and test

### Steps to Reproduce
1. Create a new `TelegramClient` session with `api-id-1` and `api-hash-1`
	```python
	from telethon import TelegramClient

	api_id = valid-api-id
	api_hash = 'valid-api-hash'
	client = TelegramClient('test', api_id, api_hash)

	async def main():
	    # ... rest of code ... #

	with client:
	    client.loop.run_until_complete(main())
	```
	2. Do whatever. First run will require to authenticate and create a session with Telegram and the local sqlite database - `test.session`.
	3. Do not add `client.log_out()` in the code.
4. Change values for `api_id` or `api_hash` in the code
	```python
	from telethon import TelegramClient

	api_id = 1			# any non-zero integer
	api_hash = 'string'	# any string
	client = TelegramClient('test', api_id, api_hash)

	async def main():
	    # ... rest of code ... #

	with client:
	    client.loop.run_until_complete(main())
	```
5. Run the code again

### Expected behaviour
`TelegramClient` should RE-validate the session against `api_id` and `api_hash`.

### Actual behaviour
`TelegramClient` re-uses session database `test.session` to establish connection with Telegram irrespective of the validity of API ID or API hash .

### Security impact

Anyone who has access to the session file can access said account even if they did not directly authenticate their client. People may accidentally check-in their session files and it can be re-used by malicious actors.

I do understand that the session parameter should also change with every change to the API ID and API hash. But for beginners playing around with the library, this could be potentially dangerous.

---
I started with the very basic client described in the `TelegramClient` module's [documentation](https://docs.telethon.dev/en/latest/modules/client.html). I progressed from there and built the rest of my functionality. I didn't bother to go back to the `client.*` methods like `client.connect()`, `client.sign_in()` or `client.start()` because I was already authenticated the first time. I found them only after I hit this issue and then went looking for the **right** way to authenticate sessions.

Alternatively, if this is expected behaviour, it would good to update the documentation to indicate that `api_id` and `api_hash` are only used once to create the session and then the session will be used henceforth.
I know it is not practical to ask for the baseclient's structure to be changed. Ideally, I would get it better if the client authentication flow looked something like : 
```python
from telethon import TelegramClient

session_file = 'test.session'
if session_file:
	client = TelegramClient.use_session(session_file)
else:
	api_id = 1				# any non-zero integer
	api_hash = 'string'	# any string
	client = TelegramClient.create_session(session_file, api_id, api_hash)

async def main():
    # ... rest of code ... #

with client:
    client.loop.run_until_complete(main())
```

**Comment by Lonami** [comment]
Thanks for the detailed report. This behavior is fine (in fact I think some people rely on this, since they know they have a valid session they don't bother writing out a valid API ID/hash). Even if the library added checks, malicious actors could remove those checks or just stick to an older version of the library, and it would be potentially annoying / confusing for other users.

The Telegram server could technically enforce that the connection is initialized and uses the same API ID as it did when the user logged in, but it doesn't, and like I said offline checks can be removed/skipped so there's not much use in adding those.

Users who accidentally commit their session should immediately revoke it from another application's settings (or via Telethon itself). Using the same session at the same time from two different locations should cause Telegram to discard the session either way (for safety measures).

I don't think this is worth documenting, because the API ID and hash should always be present in the application, ready to be used when needed, and I don't want more people relying on this behavior.
