### ISSUE TITLE
Problem with pip install Telethon==0.11.3

### ISSUE THREAD

**Issue by einali** [LonamiWebs/Telethon#157]
when i used pip to install Telethon new version via:
pip install -r requirments.txt
i got this error:
No files/directories in /tmp/pip-build-yq3h_vjo/Telethon/pip-egg-info (from PKG-INFO)

note:
i updated pip before install requirements
i run this command on fresh python installed docker container!
i did not faced same problem with older versions

best!

**Comment by Lonami** [comment]
> i did not faced same problem with older versions

I was having issues when pushing new changes to `pip`. It seems like they're working on remaking it from scratch and it wouldn't allow me to upload several files, as I used to do (`sdist` and `bdist_wheel`, which they renamed too).

This is the URL that popped up on a failed attempt: https://mail.python.org/pipermail/distutils-sig/2017-June/030766.html.

Not sure what to do, guess I will have to retry, but I need a new version for that (`pip` won't let me simply upload a new file as `v0.11.3`, which is nice in its way, but annoying because I mess up often).

**Comment by menasheh** [comment]
0.11,4 works now

**Comment by Lonami** [comment]
Yeah I could upload the wheel thanks @menasheh
