### ISSUE TITLE
Discord group for telethon?

### ISSUE THREAD

**Issue by KweezyPlay** [LonamiWebs/Telethon#1585]
would be cool if you create discord group to ask questions about docs and just to talk

**Comment by Lonami** [comment]
I don't expect anyone to ask here, because if they're using a library for Telegram the most obvious thing is that they will have a Telegram account and use Telegram on a daily basis. Regardless, I've created https://discord.gg/TFHhQJM. Please tell me your Discord username, since you seem to be willing to participate in Discord, you might make for a good moderator.

**Comment by KweezyPlay** [comment]
! a Kw
