### ISSUE TITLE
how  to cache downloaded chats?

### ISSUE THREAD

**Issue by alirezaafzalaghaei** [LonamiWebs/Telethon#163]
Is there any built-in way to cache downloaded chats? For example channel cache, views and ...

**Comment by Lonami** [comment]
> Is there any built-in way to cache downloaded chats?

Depends on your needs. If all you need is to serialize the data, you can use the `BinaryWriter` and `BinaryReader` just like Telethon does, but loading it will probably break on a scheme upgrade.

Or, you could just save the ID/hash pair, since it's what you need to access said chat.

Or, make up your own way to serialize it since you know the type beforehand (a chat), and decide what you want to keep.
