### ISSUE TITLE
Global search gone

### ISSUE THREAD

**Issue by DeepBorys** [LonamiWebs/Telethon#1653]
I have been using Telethon to search for channels on Telegram. At some point my search results stopped showing the global results, both for API queries as well as on my mobile. 

Tried a bunch of different things and after I filled out my profile information the global search came back both for phone and API, it seems so random.

Anyone had similar issues? Is there some rate limit that works silently and turns off global search results? Should I limit how much i query Telegram?

Thanks guys.

**Comment by Lonami** [comment]
This is the first time I hear about it (I know there are false negatives because Telegram caches empty results for a while). Have you tried using the raw API method to perform the global search? Does it also happen in official clients (I assume yes since you said "phone" too, but to confirm)? Can you consistently trigger this behaviour? If so, how?

**Comment by DeepBorys** [comment]
I was using this function below to find groups.
```
result = client(functions.contacts.SearchRequest(q=query,limit=100))
```
I was also logged in from Desktop on my Mac and from my Mobile. Both devices started showing only search results from channels I have already joined and private messages. No global search. My code snippet that was returning a bunch of results stopped returning anything.

I did the following steps.

1. Terminated all sessions.
2. Cleaned the cache.
3. Filled out my profile info.

After few minutes the global search came back and it has been working since then. No idea what triggered the problem, and how to recreate it.

**Comment by Lonami** [comment]
Ah, contact search, not global message search. Contact search is a way to discover a lot of usernames, and resolving username is very expensive. I wouldn't be surprised if Telegram is limitting server side (to avoid leaking too many new entities), but still returning actual contacts because the search has to work (so no flood wait). Closing, since you're using raw API, there is nothing to fix on the Telethon side.

**Comment by Lonami** [comment]
Actually this might be a temporary Telegram issue. It's down right now and I've just seen others complain :)

**Comment by DeepBorys** [comment]
I got limited. 

```
telethon.errors.rpcerrorlist.FloodWaitError: A wait of 576 seconds is required (caused by InvokeWithLayerRequest)
```

Chat and back functionality came back after 10 minutes, but it took around one hour for the global search to come back.

Thank you for the help.
