### ISSUE TITLE
update handler for channel messages

### ISSUE THREAD

**Issue by alirezaafzalaghaei** [LonamiWebs/Telethon#167]
i want to show a message when a channel send new message. After some tries i wrote this:
```
def update_handler(update_object):
    if type(update_object) is UpdatesTg:
        print(update_object)
```
My first question is why type of `update_object` for new channel message isn't `UpdateNewChannelMessage`?
And my second is: How can i convert this `update_object` to an `channel entity`?

**Comment by icoprimers** [comment]
Ok let me help you a little bit on this. It took me a while to figure out too because I'm not an experienced programmer. I don't have my scripts with me right now so maybe I'm using the wrong words to describe it but I think it should help you out.

First look at the UpdatesTg object: https://pypkg.com/pypi/telethon/f/telethon/tl/types/updates_tg.py

You see the class is instantiated like this: 
    def __init__(self, updates, users, chats, date, seq):
        """
        :param updates: Telegram type: "Update". Must be a list.
        :param users: Telegram type: "User". Must be a list.
        :param chats: Telegram type: "Chat". Must be a list.
        :param date: Telegram type: "date".
        :param seq: Telegram type: "int".

So when you receive such a class you can iterate through the lists Update, User and Chat.  These lists contain objects, and these objects have constructors.

To get you started:
`
updates = iter(update_object.updates)
try:
    while updates:
        update = next(updates)
        print(update)
except StopIteration:
    pass    
`

**Comment by Lonami** [comment]
> First look at the UpdatesTg object: https://pypkg.com/pypi/telethon/f/telethon/tl/types/updates_tg.py

Nice site.

> ```
> updates = iter(update_object.updates)
> try:
>    while updates:
>        update = next(updates)
>        print(update)
> except StopIteration:
>    pass    
> ```

You can also just do:
```python
for update in update_object.updates:
    print(update)
    # Or with a nicer format, `print(update.stringify())`
```

> My first question is why type of `update_object` for new channel message isn't `UpdateNewChannelMessage`

The [wiki](https://github.com/LonamiWebs/Telethon/wiki/Working-with-updates) now explains that Telegram may send you updates with no special treatment, i.e., you will have access to what Telegram sends, which I admit is not the most convenient way to work with it, but gives you a lot of control.

Also thanks for the help @icoprimers I didn't really know what to reply when the issue was posted…
