### ISSUE TITLE
telethon.events.messagedeleted.MessageDeleted

### ISSUE THREAD

**Issue by uzlov** [LonamiWebs/Telethon#1694]
> Note that this event isn’t 100% reliable, since Telegram doesn’t always notify the clients that a message was deleted.

Will be cool to have some method for get the full list of deleted messages. If it's possible.
Or mb you have any ideas how to do it?

**Comment by Lonami** [comment]
Other than the admin log, or monitoring the entire history and fetching it every now and then to find what messages are gone missing, the reliability of this update is up to Telegram to decide, and I doubt it can be improved anyhow. I haven't done thorough testing, much less recently, so that doc part may be completely wrong.

**Comment by uzlov** [comment]
> that doc part may be completely wrong.

sad, but the doc is looking correct

actually, the logic ~like with new messages (https://github.com/LonamiWebs/Telethon/issues/1676) some time ago
if use account, which is used for start telethon, for the deleting of messages - all events is existing
else - most part of deleted messages is not fire the event((
