### ISSUE TITLE
Get peer from user_id

### ISSUE THREAD

**Issue by seby2000** [LonamiWebs/Telethon#181]
When i receive this type of update "UpdateShortMessage" how can i send a response?
 ```
{UpdateShortMessage: {out: None, mentioned: None, media_unread: None, silent: None, id: 134, user_id: 227987657, message: "f", pts: 194, pts_count: 1, date: 2017-07-31 15:16:08, fwd_from: None, via_bot_id: None, reply_to_msg_id: None, entities: []}}
```
I can view only the id of the sender but not the peer so how can i get the input peer from the id?

**Comment by Lonami** [comment]
Telegram should send the list of users [via some other updates](https://lonamiwebs.github.io/Telethon/constructors/updates.html). You should intercept these and keep an internal database with all the known users, so that you can map `{id: user}`. Unlike other projects, Telethon doesn't do this for you (yet).

**Comment by seby2000** [comment]
> Unlike other projects, Telethon doesn't do this for you (yet).

I know, In fact, I'm doing it. But I'm using the hash for the groups and username for the users, not the id. It stores `(hash or username): input_peer` each time it sends a message for example or when it joins in a group. 

> Telegram should send the list of users via some other updates.

This does not. I received a message from this user for the first time and I just received this update "UpdateShortMessage"

**Comment by seby2000** [comment]
maybe this method will work? https://lonamiwebs.github.io/Telethon/methods/users/get_full_user.html

**Comment by Lonami** [comment]
That method should work, yes.

**Comment by soermejo** [comment]
Is there anothere similar method for channel (i see getfullchannel but he
need Chat not a channel_id)

Il 31/Lug/2017 17:15, "Lonami" <notifications@github.com> ha scritto:

That method should work, yes.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/LonamiWebs/Telethon/issues/181#issuecomment-319098647>,
or mute the thread

**Comment by Lonami** [comment]
Doesn't seem like it then. Again though, Telegram should send the channels through some other updates mechanism, but if you get updates from a channel (which cannot talk to you, unless it's on your dialogs), you probably need to get it via caching everyone from `get_dialogs()`.
