### ISSUE TITLE
What is the diff between log_out and disconnect TelegramClient methods?

### ISSUE THREAD

**Issue by alexvelickiy** [LonamiWebs/Telethon#191]
What is the diff between log_out and disconnect TelegramClient methods?

**Comment by Lonami** [comment]
`.log_out` logs you out from the existing `Session`, also deleting the file itself. `.disconnect()` will simply disconnect you from the Telegram server, while keeping your `.session` file available for a next run, so that you don't need to call `.sign_in` (which you would have to if you logged out).

**Comment by alexvelickiy** [comment]
Thank you. And thank you for great package.

Where can I read about Telethon sessions and what are they used for?

**Comment by Lonami** [comment]
You could check the [`session.py`](https://github.com/LonamiWebs/Telethon/blob/master/telethon/tl/session.py) file itself. They're used to keep track of the sequence number, secret used to encrypt the messages, and other handy information. Some usage examples over [`mtproto_sender.py`](https://github.com/LonamiWebs/Telethon/blob/master/telethon/network/mtproto_sender.py), [`telegram_bare_client.py`](https://github.com/LonamiWebs/Telethon/blob/master/telethon/telegram_bare_client.py), etc.
