### ISSUE TITLE
Stop receiving updated with add_update_handler()

### ISSUE THREAD

**Issue by alexvelickiy** [LonamiWebs/Telethon#202]
Hi,

I'm using v. 0.11.5. Sometimes (couldn't find conditions to reproduce it), I suddenly stop receiving updates from handler set by add_update_handler() method. Sometimes it's followed by (or preceded by - I don't know) that I get last update (updates) duplicate.

Possibly it's due to the case that it's possible that two clients with same sessions run in different threads, both use add_update_handler() and could get disconnected?

Update: just notice that my app uses two different sessions file for same user. It happened accidentally. One session file is used by clients to retrieve dialogs, another is used to retrieve dialogs and use add_update_handler().

**Comment by Lonami** [comment]
> I get last update (updates) duplicate.

Since I don't care about the `seq` number for the updates yes, the official documentation says updates may come in wrong order, or be duplicated.

> Update: just notice that my app uses two different sessions file for same user.

Slightly a strange situation, two sessions? You've logged in with a code on both, right? If you want to have two connections and avoid two sessions for the same user, you should avoid this case and call [`create_new_connection`](https://github.com/LonamiWebs/Telethon/blob/afcddfd7c155cd88e73075c7faf2aaa39b065e99/telethon/telegram_client.py#L158) instead.

Once again the situation with updates right now is not the most optimal because I need to handle [a bunch](https://github.com/LonamiWebs/Telethon/tree/better-updates) of [other stuff](https://core.telegram.org/api/updates).

**Comment by alexvelickiy** [comment]
I think I got the issue. 

I managed to make the app use single session file. And the following happening, one thread start listening to updates (session "sequence" is say 100). Then another thread that uses same session file gets dialogs list. Now session "sequence" is 103 and I stop receiving updates.

**Comment by alexvelickiy** [comment]
Any ideas @Lonami ?
I've just realized that these telethon clients reside in different processes.

**Comment by Lonami** [comment]
From my experience, clients created with `.create_new_connection()` don't *seem* to receive updates. If you have created two clients, and logged in by entering the code Telegram sends on both, they should be independent despite the thread they live in.

I don't have a production use for Telethon, so I don't really test all these features on the long term (like running a script for days), and I don't know when, why, or where it can be failing. Again Telegram may just stop sending updates since we never call `.getDifference`, but that's just a guess and until it's implemented, we can't check if that's the reason.

**Comment by alexvelickiy** [comment]
I don't use `.create_new_connection()`. Both clients are created with constructor of `TelegramClient()`.
As I use same session for both clients, I entered Telegram code once.

The problem here as I understood not such about updates but about two processes working with same session name (and thus session file). Update handler seem to update "sequence" value storing previous value. So it doesn't update actual value from session file, but stored beforehand.

What is in general proper approach to connect to same Telegram user from two processes, threads? Should each work with different session names (and thus files)?

**Comment by Lonami** [comment]
> As I use same session for both clients

You shouldn't do that. The clients are not aware of each other and there may be synchronization issues, when reading or saving the session file for instance. If you need two connections, you should use `.create_new_connection()` instead.

You *could* try to pass the `client1.session` as the session for `client2`. That might help with the synchronization but I'm not sure how Telegram will behave.

> What is in general proper approach to connect to same Telegram user from two processes, threads? 

`TelegramClient.create_new_connection()`

> Should each work with different session names (and thus files)?

They would be completely independent, which is probably not what you intend.

**Comment by alexvelickiy** [comment]
I found out why I stop getting updates sometimes. It's due to `ConnectionResetError `exception in `TelegramClient._updates_thread_method()`. This exception leads to reconnection and on reconnection that calls `_set_updates_thread(running=False) ` but nothing sets threads running back.

**Comment by Lonami** [comment]
> Is that normal situation of losing connection?

No, the updates thread should restart itself.

**Comment by alexvelickiy** [comment]
`reconnect()` method call `disconnect()` and `connect()`. The first one stops update thread with `self._set_updates_thread(running=False)`, but connect doesn't call `self._set_updates_thread(running=True)`.

To solve this, `connect()` method of `TelegramClient` should check if there are any registered update handlers and if any, start update thread.

**Comment by Lonami** [comment]
Would you like to make a pull request yourself?

**Comment by alexvelickiy** [comment]
Never did that, but I'll try.

**Comment by Lonami** [comment]
Click the Fork button (top right), clone the repository with your own user (`git clone https://github.com/alexvelickiy/Telethon.git`), add changes (usual, `git add .`, `git commit`, `git push`), and then from your repository there should be some sort of "Make pull request".

**Comment by alexvelickiy** [comment]
Done.

BTW, when receiving updated of `UpdatesTg` type, I always have `UpdatesTg.seq` as 0.
Is that as it must be? Because on Telegram docs they say I have to compare seq value to previous one (I think).

Asking because currently I'm checking for duplicates by `UpdatesTg.date`, which I don't think is ideal solution as I suppose two updates may have same date.

Message pts doesn't help as it seems to be incremented independently for each Telegram channel.

**Comment by Lonami** [comment]
> I always have UpdatesTg.seq as 0. Is that as it must be?

Sorry, but I have no idea! Maybe it's 0 because we never called [`GetStateRequest`](https://lonamiwebs.github.io/Telethon/methods/updates/get_state.html) in the first place?

> Telegram docs they say I have to compare seq value to previous one (I think).

This is correct, but it's not *you* who should do it but rather the library itself (letting everyone implement their own version of how to handle updates is not a good idea). Remember there's a branch with a bit of code done, [better-updates](https://github.com/LonamiWebs/Telethon/tree/better-updates), that attempts at preserving and using this state.

> I'm checking for duplicate

Again, this should be done at the library level :/

> as I suppose two updates may have same date.

Not sure about that one either, but it might be possible.

**Comment by Lonami** [comment]
Is this fixed with #217?

**Comment by robsske** [comment]
Tested the new branch, its not solved yet..

**Comment by Lonami** [comment]
When I added the new `ReadThread`, I forgot to add back a periodic `PingRequest` yet again. I need to think of a good way to call that from within a thread that's supposed to just be reading.

**Comment by Lonami** [comment]
Closing in favor of #237.
