### ISSUE TITLE
See and Terminate other sessions

### ISSUE THREAD

**Issue by hamed169** [LonamiWebs/Telethon#228]
Is there any method to see or terminate other sessions?
DestroySessionRequest has a session_id parameter that I don't know how can I fill it!

**Comment by Lonami** [comment]
They're called [`authorizations`](https://lonamiwebs.github.io/Telethon/?q=authorization), not `sessions`. [`GetAuthorizationsRequest`](https://lonamiwebs.github.io/Telethon/methods/account/get_authorizations.html) to get a list, [`ResetAuthorizationsRequest`](https://lonamiwebs.github.io/Telethon/methods/auth/reset_authorizations.html) to terminate all. I won't label this as `RTFM` because I had to look over [Telegram Desktop's source](https://github.com/telegramdesktop/tdesktop/blob/197cdc3928d2403814c147f8394ef42ed427c9d8/Telegram/SourceFiles/boxes/sessions_box.cpp).
