### ISSUE TITLE
question about telethon fetch access_hass by user_id

### ISSUE THREAD

**Issue by mohammadmirshahi** [LonamiWebs/Telethon#245]
### Help

 
   https://stackoverflow.com/q/46130404/6926898

**Comment by Lonami** [comment]
You can't. #244 is similar.

**Comment by Lonami** [comment]
Since you asked it clearly (although you removed the issue template…) I'll just answer it here for anyone else who comes accross. The way to get over this is to cache **every user** from **every request and update object**, so then you can just look up by the ID. Telethon doesn't do that yet, so the only way currently is to implement it yourself. That, or wait until me or someone else does it…

If the user just has an username, use `ResolveUsernameRequest`.
