### ISSUE TITLE
getHistory seems to cap the retrieval limit at 100

### ISSUE THREAD

**Issue by jlin929** [LonamiWebs/Telethon#261]
It seems that I'm only able to get the last 100 message from a chat even if I set my limit to more than 100.  Is there something I'm missing?   Following is my code. 

total_count, messages, senders = self.get_message_history(entity, limit=5000)
print(total_count)
msgIds = []
for message in messages:
    msgIds.append(message.id)
print(len(msgIds))

**Comment by alirezaafzalaghaei** [comment]
You can do something like this: https://github.com/LonamiWebs/Telethon/wiki/Retrieving-all-dialogs

**Comment by jlin929** [comment]
I ended up using a for loop with "add_offset" to grab the data i need !

**Comment by Lonami** [comment]
Yeah Telegram has a hard limit like this for a reason (otherwise you would be able to return millions of messages with a single call… which would not work). Just use an offset, as you said you're doing. I personally prefer the `offset_date` since it's the one that works most reliably for me.

Someone has suggested that setting an higher limit should be handled by the library itself, so it may be implemented. Not sure when, or if it will, though.
