### ISSUE TITLE
Document requirement of accepting ToS Updates

### ISSUE THREAD

**Issue by vegeta1k95** [LonamiWebs/Telethon#3040]
As it is written at the official Telegram [Docs](https://core.telegram.org/api/config#client-configuration):

> After signing up, or when logging in as an existing user, apps are supposed to call help.getTermsOfServiceUpdate to check for any updates to the Terms of Service; **this call should be repeated after expires seconds have elapsed**.
> If an update to the Terms Of Service is available, clients are supposed to show a consent popup; if accepted, clients should call help.acceptTermsOfService, providing the termsOfService id JSON object; in case of denial, clients are to delete the account using account.deleteAccount, providing Decline ToS update as deletion reason.

Currently, there is no in-library application for the `GetTermsOfServiceUpdateRequest()`.

Do we want this to be automatically queried by the client? Or maybe introduce user-friendly methods, e.g. like:
```await client.check_tos_update(accept=True)```

Or you want this routine to be implemented only by clients, not by library?

**Comment by Lonami** [comment]
Given the library is mostly used to automate tasks, I don't think we can do this properly. What's is the library going to do, block and prompt for input? What if it's a GUI app, or web? What if there's nobody there? Should the script just exit? Also, deleting the entire account seems extremely excessive and dangerous.

I think this should be done by apps built upon the library, not Telethon itself, because they're the one who can decide what to do. Closing.

**Comment by vegeta1k95** [comment]
@Lonami Then I think it would be worth mentioning somewhere in the docs, that, _theoretically_, failing to accept updated ToS may lead to automated deactivation of acctounts. So then users are advice to implement this routine properly.

**Comment by Lonami** [comment]
Yes, that could be done, although I'm guessing most people also have Telegram on different devices (where they do accept the ToS).
