### ISSUE TITLE
Wait for all event handlers to finish

### ISSUE THREAD

**Issue by sgrontflix** [LonamiWebs/Telethon#3146]
Hi!

It'd be nice to have a function that waits for all event handlers to finish. Something like a join(), but for event handlers.

For example:
- I register a certain function `foo()` to handle the `NewMessage` event
- I constantly receive new messages and have multiple `foo`s running
- Each `foo()` modifies a local variable `bar` that's stored in a txt file every 5 minutes
- I decide to kill the script using CTRL+C, so I remove the event handler, but I may still have some `foo`s writing data to `bar` that I need to save before exiting!

I wasn't able to find any function that achieves this in the documentation and that would be very convenient to have.

Have a nice day!

**Comment by Lonami** [comment]
Would a function like `client.safely_remove_all_handlers()` (with a better name) suit your needs? If you're interested in coding this up yourself I can offer guidance.

**Comment by sgrontflix** [comment]
> 
> 
> Would a function like `client.safely_remove_all_handlers()` (with a better name) suit your needs? If you're interested in coding this up yourself I can offer guidance.

Sure! I'd really like some help with that :)

**Comment by Lonami** [comment]
The code path an update follows when it is received from Telegram starts here:

https://github.com/LonamiWebs/Telethon/blob/391fbab67427e21514a35443acd6a0061d4f8d2b/telethon/client/updates.py#L303

It basically checks the type and calls a method to handler the inner, individual updates, where the interesting part is:

https://github.com/LonamiWebs/Telethon/blob/391fbab67427e21514a35443acd6a0061d4f8d2b/telethon/client/updates.py#L319-L337

Depending on whether sequential updates are enabled or not (`self._dispatching_updates_queue is None`), we either spawn a task to handle it directly or run a loop that will pop from the queue. ` _dispatch_update` is responsible for calling whatever handlers are registered.

Notice how the tasks are stored in `self._updates_queue`, so from the proposed `safely_remove_all_handlers` method, we can simply iterate the queue and `await` all of them (or use `asyncio.wait` to do so concurrently and for nicer cancellation). This should probably introduce some sort of flag in the client to prevent `add_event_handler` from being executed while this runs (maybe just raise if you try to add an event while we're safely removing the others).

The task from `_dispatch_queue_updates` is currently not stored, so perhaps we should refactor it a tiny bit or just add another variable (maybe `_dispatching_updates_queue` could store the task instead).

**Comment by Lonami** [comment]
The idea would be to have a new `async def` inside the `updates.py` file which would both remove all handlers and await all tasks inside `updates_queue`, while also taking care when *not* using the queue to store tasks. (User code should not access private fields as they are prone to change between small versions, hence the need for a public method.)

Rather than `self.remove_event_handler(self.message_handler)`, your code would be `await self.safely_remove_all_handlers()`.

**Comment by sgrontflix** [comment]
I think there was a misunderstanding because while I want not to receive messages anymore by removing the `message_handler`, I just want to wait for the `message_handler`s that were already called to finish executing, if that makes sense.

By running `await self.safely_remove_all_handlers()`, all of my message handlers would be gone, right? I only want to wait for the `message_handler` coroutines that are still running to finish.

**Comment by Lonami** [comment]
You want to only remove 1 handler and wait for tasks running that 1 handler to finish. That's not as trivial, because a single task can be triggering many handlers in order. We don't know beforehand which handlers will fire given an update (and any handler can prevent the propagation of the update to subsequent handlers).

That's why my idea was to have a method that would remove all handlers and wait for all updates to be processed.

**Comment by sgrontflix** [comment]
Oh, okay.

Do you think this would do the trick?
```
async def safely_remove_all_handlers():
    self.remove_event_handler()

    for update in self._updates_queue:
        asyncio.wait(update)
```

I have no idea how to check if `updates_queue` is not being used to store new tasks... Could you lend me a hand?

**Comment by Lonami** [comment]
> Do you think this would do the trick?

Not quite, `remove_event_handler` expects a callback to remove. We would probably just clear the field holding all handlers internally.

`asyncio.wait` works a bit differently, but the Python documentation in https://docs.python.org/3/library/asyncio.html does a good job explaining it.

`_updates_queue` contents depend on the same `self._dispatching_updates_queue is None` condition (since that's what is used to decide what to store). However, some additional changes will be required to handle when the queue does *not* store the tasks.

**Comment by sgrontflix** [comment]
>Not quite, remove_event_handler expects a callback to remove. We would probably just clear the field holding all handlers internally.

Do I need to clear `event_builders`?

>_updates_queue contents depend on the same self._dispatching_updates_queue is None condition (since that's what is used to decide what to store). However, some additional changes will be required to handle when the queue does not store the tasks.

I can't just check it with an `if`, correct? Because if dispatching_updates_queue is not None, it would just skip it. Also, what changes should I add to handle the queue not storing tasks?

This is my current code:
```
async def safely_remove_all_handlers():
    self.remove_event_handler()
    
    self._dispatching_updates_queue is None:
        await asyncio.wait(self._updates_queue)
```

**Comment by Lonami** [comment]
> Do I need to clear `event_builders`?

In essence, yes.

> I can't just check it with an `if` statement, correct?

You can, after adjusting the condition to suit your needs. Maybe it needs to be negated. I haven't dug into it.

> Also, what changes should I add to handle the queue not storing tasks?

At this point I'd be the one writing the code which would defeat the purpose of offering "a bit of guidance". Don't worry if you can't do it on the first try, or if something more important comes along.

**Comment by sgrontflix** [comment]
>At this point I'd be the one writing the code which would defeat the purpose of offering "a bit of guidance". Don't worry if you can't do it on the first try, or if something more important comes along.

That's fair. I think I'll just give up because I've been stuck on this problem for way too long and understanding how the source code works seems pretty intimidating ahah. Thank you anyway!

**Comment by Lonami** [comment]
This is unlikely to happen in the near future so I will be closing the issue. We can reopen it if there's still interest once the time is right.
