### ISSUE TITLE
message.click runs significantly slower after the message got updated

### ISSUE THREAD

**Issue by stanleyws** [LonamiWebs/Telethon#3217]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
...
await event.message.click(0, 0)
await asyncio.sleep(1)
await event.message.click(0, 1) #original message gets updated here
await asyncio.sleep(1)
last_msg=await client.get_messages(my_chat, ids=message_id)
await last_msg.click(0, 0)
...
```

What I'm trying to achieve is to click a series of buttons automatically in a message sent by a bot. It should click the first button, wait for 1 second, then click the second button, wait for another 1 second, then click the first button again. The original message will get updated after the second button click, so I used get_messages to get the updated message. Apparently, the click() function runs significantly slower when the message got updated. The second and third click() takes about 15 seconds to complete, but there's no error message.

**Comment by Lonami** [comment]
`click` takes as long as the bot takes to `answer` your callback query. The bot may not be responding, and the request timing out after some time. This cannot be fixed because it's how the request works. Instead the bot should be fixed to answer.

**Comment by Lonami** [comment]
You can confirm whether the bot is timing out by checking if the method returns `None`.

**Comment by rezahx** [comment]
I have the same problem!
When I work with the bot manually, it is fast. However, when I want to use this method, it takes 15 seconds longer.

**Comment by Lonami** [comment]
As stated, the way invoking raw API works is, Telethon sends the request to Telegram, and `await` signals that the method won't return until Telegram sends a response.

What's slow is Telegram sending the response. Because Telegram waits for the bot to answer. And if the bot does not answer, it times out.

If you want to run the request "in the background", you can use `asyncio` for that as explained in their documentation. This is not a "feature" that should be in Telethon.
