### ISSUE TITLE
Make TelegramClient.create_new_connection() return TelegramClient

### ISSUE THREAD

**Issue by alexvelickiy** [LonamiWebs/Telethon#327]
Hi,

Is it possible to make TelegramClient.create_new_connection() return not TelegramBareClient but TelegramClient in order to make it possible to use download_media() with newly returned client,

**Comment by Lonami** [comment]
You *really* should upgrade. `.create_new_connection()` has been deprecated, and using another thread which isn't the main one will create a temporary connection for you. Note that I need to enhance downloading media from separate threads because it will create a temporary connection for every chunk, but it will work.
