### ISSUE TITLE
ban account after create session

### ISSUE THREAD

**Issue by Irbis01** [LonamiWebs/Telethon#3861]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon.sync import TelegramClient
username="my_username"
api_id=my_api_id
api_hash="my_api_hash"
phone="+79*********"
client = TelegramClient(username, api_id, api_hash)
client.start(phone=phone)
```

account was banned after 10 min. api_id and api_hash i got correct from https://my.telegram.org/auth
I am using real phone number on the real phone. I register new acc in oficial app Telegram, set photo in this app. Then i wait 1 hour - all the ok. Nice! Then i create app_id, wait 10 min - all is ok. Then i try to start TelegramClient from Telethon. 10 min - ban. 
I tried this 3 times on different real phone numbers - all of them will be banned.

Phone have a positive balance and can receive/send sms and calls

**Comment by Lonami** [comment]
See #824.

**Comment by Irbis01** [comment]
> See #824.

i saw this issue. This solution is using 0.18 version? Right?
I restore 2 from 3 banned accs from telegram support. I try using another library(not telethon) and they works fine right now. I will continue to watch them.
So... i think its problem not with my real phone numbers

**Comment by Lonami** [comment]
The summary is Telegram decides the bans. While the version used may or not affect Telegram's decision on banning, it's still Telegram's decision, and not something the library can really "fix". I do personally find Telegram has recently been more serious about banning potential spam accounts.

**Comment by Irbis01** [comment]
so why my accounts not banned when i using other library? I restore my accounts. They working fine right now with other libraries(not telethon)
Telegram detect when i use telethon? 

My problem with telethon not fixed. Why this issue was closed?

**Comment by Lonami** [comment]
This issue was closed because the bans are

> still Telegram's decision, and not something the library can really "fix".

I have seen other libraries getting bans while Telethon didn't. Again it's not something I can fix.

**Comment by Irbis01** [comment]
Heh. So ... ok. Many peoples in different chats spoke about ban with using telethon, not other libs. My experiens proof them sentence. Maybe Telegram doesn't like this library? Did you try connect with the Telegram?

**Comment by dev-sourabh** [comment]
Hi,
@Irbis01 What are the other libraries for telegram in python?

**Comment by ShamilSd-ux** [comment]
My Account is also banned on using telethon string generation. How to unban it asap?.

**Comment by malachychidera** [comment]
> so why my accounts not banned when i using other library? I restore my accounts. They working fine right now with other libraries(not telethon) Telegram detect when i use telethon?
> 
> My problem with telethon not fixed. Why this issue was closed?

Which other libraries are you using, My number has been banned like 3 times and these numbers are real users number

**Comment by M4jx** [comment]
I tried to do some development today using this library, however, the account got banned randomly after doing multiple runs of the program. The program was very simple and only contained the sample code in the documentation with minimal modifications.

One thing to mention is that:
- I had VPN on during development.
- I had the account logged in using telegram's web version from one IP address and the development was running on another machines with different IP address.
- Multiple sessions were created in short time during debugging (telethon client.start())

I will try to restore the account through telegram support and will try to:
- Not use any VPN during development
- Login from one IP address at a time.

I will check if that works and will update my comment.


-----------

Update 1:
I have tried making an account using temporary phone number. The account works for less an hour and then it gets banned. Even though I am not doing anything suspicious, only joining 2 public channels and trying to read message events. 
Not sure if it is related to being registered with a phone number from online services or not. I guess it is because of it.

Update 2:
After reading the exception, it turned out to be caused by _ResolveUsernameRequest_. Not sure if it has to do with who owns the channel (the user that is running telethon or another external user). It is not possible to know the real issue because debugging is not that easy when you get banned and need a new account every time (Telegram, please, take it easy).

Solution:
Do not use the channel name to reference channels, use the channel ID instead (the one starting with -100....). 
Ref. https://github.com/LonamiWebs/Telethon/issues/494
