### ISSUE TITLE
Update the release from `v1.24` branch

### ISSUE THREAD

**Issue by egormanga** [LonamiWebs/Telethon#3880]
Telethon is getting pretty outdated now (missing some key features such as emoji reactions and `send_as`). It's time to clean up the code and make a new PyPI release (`v1.21.1`, I guess).

Should also update the `v1.24` branch itself from `master` with the aforementioned features.

Probably requires #3870 to be resolved first.

**Comment by Lonami** [comment]
The problem with this is that there were some other changes with the v1.24 branch that make external session storages break. Because of this, it's a breaking change which should not be released in the v1 series. However, v2 is another thing entirely, which is nowhere near ready. This should explain the lack of a new release to PyPi and the existence of the v1.24 branch (a necessity, because it was starting to be too old and breaking too).

**Comment by egormanga** [comment]
Well, then let's move on with v2 for now (to once become v3), and for the time being release a v2 with the currently available breaking changes?

The code in master branch really doesn't work, in multiple ways.

**Comment by Lonami** [comment]
Nah that's not my plan, I'd rather maintain fixes for v1.24 for as long as it takes me to finish v2, and make its installation process more prominent if needed.

**Comment by egormanga** [comment]
Sure, however you decide. Yet I'd be more pleased to be able to use `master` (or, rather, a separate **stable** up-to-date branch) for now, so not closing.

**Comment by Lonami** [comment]
Closing since this was done (v1.24 is now on PyPi and I intend to keep updating the layer of that, since the v1.24 branch is for the v1 series).
