### ISSUE TITLE
Telethon not working on new bots if bot api_ids is higher than 2^31

### ISSUE THREAD

**Issue by EmreKarslan** [LonamiWebs/Telethon#3892]
Today I created a new bot to do something. My other bots' API ids are lower than 2^31 but the new bots' API ids higher than 2^31 and this causes errors in the struct.pack('<i', int) method

**Checklist**
* [X] The error is in the library's code, and not in my own.
* [X] I have searched for this issue before posting it and there isn't a duplicate.
* [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon import TelegramClient
client = TelegramClient('bot_session', 5576347382, '******')
client.start(bot_token='*****')
```
**Traceback**
```
Traceback (most recent call last):
File "C:\Users\X\Documents\Telegram_Bot_Father\lib\site-packages\telethon\tl\functions\__init__.py", line 124, in _bytes
    print(struct.pack('<i', self.api_id))
struct.error: argument out of range

```

**Comment by Lonami** [comment]
The API ID and hash are what you get from https://my.telegram.org, not the first number and second half of the bot token. Telethon talks to the Telegram servers directly and needs this value to do so (the HTTP bot API runs an intermediate layer, which works like Telethon, with a builtin API ID, which is why you don't provide one. Telethon does not have a builtin API ID, developers need their own).
