### ISSUE TITLE
[v1.24] delete event not coming unless some other event happens

### ISSUE THREAD

**Issue by kshubham506** [LonamiWebs/Telethon#3903]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [ ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
If a message is deleted it is not sent unless new message or edit message event happens in which case the below events occur and all previous delete happens.

```

**Traceback**
2022-08-21 19:36:37.168 | INFO     | telethon.client.updates:_update_loop:341 - Timeout waiting for updates expired
2022-08-21 19:36:37.170 | INFO     | telethon.client.updates:_update_loop:279 - Getting difference for channel updates

```

**Comment by Lonami** [comment]
In my experience deletion events are not very reliable. If the client or channel is not actively used I wouldn't be surprised if Telegram did not send the update at all. Message deletions are like any other updates to Telethon, so if others work and deletion doesn't it's probably Telegram's fault. It's just not a high priority for Telegram to notify about deletions so it might be choosing not to, in order to reduce load.

**Comment by kshubham506** [comment]
Yeah, that migh be. but the strange thing is as soon as I move to master branch it works perfectly, also in 1.24 branch all delet events are executed in next new or edit message events.

**Comment by Lonami** [comment]
The master branch is using an older layer. This is about the only difference, because the update handling for v1.24 was backported from master.
