### ISSUE TITLE
"Closing current connection to begin reconnect" can hang forever

### ISSUE THREAD

**Issue by milahu** [LonamiWebs/Telethon#3917]
`tg-archive --sync` was hanging for 7 days

https://github.com/knadh/tg-archive

```
2022-08-27 18:55:44,581: cryptg detected, it will be used for encryption
2022-08-27 18:55:45,194: starting Telegram sync (batch_size=1000, limit=0, wait=10, mode=standard)
2022-08-27 18:55:45,206: Connecting to 149.154.167.51:443/TcpFull...
2022-08-27 18:55:45,314: Connection to 149.154.167.51:443/TcpFull complete!
2022-08-27 18:55:45,685: fetching from last message id=3043 (2022-08-27 00:00:00)
2022-08-27 18:55:46,074: The server closed the connection
2022-08-27 18:55:46,076: Connection closed while sending data
2022-08-27 18:55:46,076: Closing current connection to begin reconnect...
^C2022-09-03 19:12:50,638: sync cancelled manually
```

the last log message is produced by

https://github.com/LonamiWebs/Telethon/blob/8df66c0b47ca06c06d8194d651267ea7d47939c3/telethon/_network/mtprotosender.py#L333

the log message `sync cancelled manually` comes from

https://github.com/knadh/tg-archive/blob/32240224f1a49b52aead1c8a4c20de4ce52f3bd4/tgarchive/__init__.py#L143

the log message `fetching from last message` comes from

https://github.com/knadh/tg-archive/blob/ba72969d4e0200f5b417c498f5969028725e52cb/tgarchive/sync.py#L34

**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [ ] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
In the [`connection.py:disconnect`](https://github.com/LonamiWebs/Telethon/blob/363c2604dfa7504c829f58be5c8a64448ffc4f62/telethon/network/connection/connection.py#L251-L274) method of the v1.24 branch, please try adding `print` or other `logging` to figure out where it's getting stuck.

It should not be getting stuck during the cancel, because those tasks only run the loops, and the loops should properly except the `CancelledError` and exit promptly. It might be `await self._writer.wait_closed()`, or perhaps how Python or the OS is somehow configured to handle connections.

If it is getting stuck in `wait_closed`, I don't know if there's much that can be done other than adding a hard timeout. Or perhaps there's a better solution I am not aware of. Unfortunately I have never experienced this issue from what I can remember.

**Comment by milahu** [comment]
sorry i dont have time to reproduce

i can think of 2 causes

* DNS timeouts
* enabling/disabling VPN

timeout + retry loop should be the simplest solution

both timeout and retry count should be configurable

**Comment by Lonami** [comment]
It might also be a Python issue, but because I could not reproduce the error, I cannot confirm if this is the case https://bugs.python.org/issue39758. I will simply add a timeout for the time being.

**Comment by Lonami** [comment]
Let me know if the above does not solve your issue (in that case, it might be that `cancel` is hanging, but I doubt it).
