### ISSUE TITLE
QR Log In doesn't work

### ISSUE THREAD

**Issue by swimmwatch** [LonamiWebs/Telethon#3922]
**Checklist**
* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/master.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
class Assistant:
    def __init__(
            self,
            telegram_client: TelegramClient,
            assistant_manager_grpc_client: AssistantManagerGrpcClient
    ):
        self.telegram_client = telegram_client
        self.assistant_manager_grpc_client = assistant_manager_grpc_client

    def _add_handlers(self):
        """
        Add Telegram handlers.
        """
        @self.telegram_client.on(events.NewMessage(outgoing=True))
        async def handle_new_own_message(event: events.NewMessage.Event):
            command_request = CommandRequest(event)
            await AssistantCommandsManager.handle(command_request)

    async def is_user_authorized(self) -> bool:
        return await self.telegram_client.is_user_authorized()

    def _create_login_qr_code(self, qr_login: QRLogin) -> Image:
        #!!!
        # Exception raises here ->
        # !!!
        return qrcode.make(qr_login.url)

    def _send_qr_code(self, img: Image):
        base64_img = Base64Image.encode(img)
        req = SendPhotoRequest(
            chat_id=assistant_manager_settings.my_telegram_id,
            caption='Please login using this QR code.',
            base64_img=base64_img
        )
        self.assistant_manager_grpc_client.stub.send_photo(req)

    async def authorize_user(self):
        qr_login = await self.telegram_client.qr_login()
        user = None
        while not user:
            # TODO: Add attempts counting process. If too much the raise exception.
            img = self._create_login_qr_code(qr_login)
            self._send_qr_code(img)
            try:
                user = await qr_login.wait(
                    assistant_settings.assistant_qr_login_timeout
                )
            except asyncio.TimeoutError:
                await qr_login.recreate()

```

**Traceback**
```
Traceback (most recent call last):
2022-09-12T15:50:52.691694411Z   File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 682, in grpc._cython.cygrpc._handle_exceptions
2022-09-12T15:50:52.691716936Z   File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 796, in _handle_rpc
2022-09-12T15:50:52.691738323Z   File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 547, in _handle_unary_unary_rpc
2022-09-12T15:50:52.691760382Z   File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 404, in _finish_handler_with_unary_response
2022-09-12T15:50:52.691781490Z   File "/app/services/assistant/grpc/server.py", line 68, in authorize_user
2022-09-12T15:50:52.691807008Z     await self.assistant.authorize_user()
2022-09-12T15:50:52.691827566Z   File "/app/services/assistant/assistant.py", line 86, in authorize_user
2022-09-12T15:50:52.691850196Z     img = self._create_login_qr_code(qr_login)
2022-09-12T15:50:52.691871883Z   File "/app/services/assistant/assistant.py", line 70, in _create_login_qr_code
2022-09-12T15:50:52.691897479Z     return qrcode.make(qr_login.url)
2022-09-12T15:50:52.691920391Z   File "/root/.cache/pypoetry/virtualenvs/telegram-assistant-9TtSrW0h-py3.10/lib/python3.10/site-packages/telethon/tl/custom/qrlogin.py", line 57, in url
2022-09-12T15:50:52.691942469Z     return 'tg://login?token={}'.format(base64.urlsafe_b64encode(self._resp.token).decode('utf-8').rstrip('='))
2022-09-12T15:50:52.691965528Z AttributeError: 'LoginTokenSuccess' object has no attribute 'token'
2022-09-12T15:51:52.622484822Z INFO:telethon.client.updates:Getting difference for account updates
2022-09-12T15:51:52.774113405Z ERROR:telethon.client.updates:Fatal error handling updates (this is a bug in Telethon, please report it)
```

**Comment by Lonami** [comment]
Are you actually trying this in the version from the master branch or the PyPi 1.25?

**Comment by swimmwatch** [comment]
Yes. I tried from GitHub (master branch) and PyPI (latest version - 1.25).

**Comment by alpdeniz** [comment]
Please see this commit:
https://github.com/alpdeniz/Telethon/commit/28126967d068e45fb16bd8d7799ded3655d8c2de

Be aware that currently the master branch is not stable. There are many other issues, however, this same edit may fix Telethon 1.25.0 as well.

**Comment by Lonami** [comment]
I intend to release the patch above after a few other fixes. If the above commit does not solve the problem for you please let me know. You can try with this command:

```
python -m pip install --upgrade https://github.com/LonamiWebs/Telethon/archive/v1.24.zip
```

**Comment by alpdeniz** [comment]
It worked. Thanks!

**Comment by Lonami** [comment]
Thanks for confirming.

**Comment by sh4dowb** [comment]
@Lonami hey, I'm still having issues with this.
```
task = asyncio.create_task(qr_login.wait(time_out))
print(await self(functions.auth.AcceptLoginTokenRequest(qr_login.token)))
await task
```

I've updated `qrlogin.py` with this to debug:
```
        async def handler(_update):
            print("RECEIVED UPDATE", _update)
            event.set()

        print('SET HANDLER')
        self._client.add_event_handler(handler, events.Raw(types.UpdateLoginToken))
```


```
SET HANDLER
Authorization(hash=4011868399309040792, device_model='iPhone 8 Plus', platform='iOS', system_version='15.0.1', api_id=xxxxx, app_name='xxxxx', app_version='8.4', date_created=datetime.datetime(2022, 9, 16, 20, 6, 30, tzinfo=datetime.timezone.utc), date_active=datetime.datetime(2022, 9, 16, 20, 6, 30, tzinfo=datetime.timezone.utc), ip='45.83.xxx.xxx', country='Malmo, Sweden', region='', current=False, official_app=True, password_pending=False, encrypted_requests_disabled=False, call_requests_disabled=False)
```

handler is never being called. Also I tried with `events.Raw` to get all events but still no updates at all.
I've tried `v1.24.zip` (version still shows as 1.25, error on your side?), master branch, 1.24 and 1.25 from pip.

Actually I'm using https://github.com/thedemons/opentele , and since it doesn't work, I'm trying to fix it.
Weirdly, when I print the sessions, all the "login attempts/sessions/devices" are showing up. But I never receive the logged in event, and when it times out I try manually to connect to the session and I'm getting `telethon.errors.rpcerrorlist.FloodWaitError: A wait of 3600 seconds is required (caused by InvokeWithLayerRequest(InitConnectionRequest(GetConfigRequest)))`

any ideas why no updates are being sent?

edit: just tried with official telegram client to scan the QR code, still, not working. times out. on telegram it's stuck as "incomplete login attempts"

**Comment by Lonami** [comment]
The v1.24 branch is called this way because it's based off the v1.24 version. But it will remain the branch for the v1 series. Maybe I should rename it.

I tried it a couple times and for some odd reason I did not get it to work reliably. This is why I asked if it was solved for the people posting in the issue, and since I got a yes I assumed it was working fine.

QR login for non-official applications in general seems kind of awkward. I tried QR login and accept from the same Telethon program, and accept would always tell me `AUTH_TOKEN_EXPIRED`. I heard some other people got banned as well (but I've personally never experienced a ban, and I've tried a ton of things with the library).

I'll try debugging this a bit more, but the main issue (`updateShort` being dispatched) has been fixed.

**Comment by Lonami** [comment]
@sh4dowb or @swimmwatch I tried logging in and it worked fine (except for the fact I have 2FA so it raised `SESSION_PASSWORD_NEEDED`). Can you confirm that it does not work for you in the latest version, which you can install with:

```
https://github.com/LonamiWebs/Telethon/archive/v1.zip
```

?

**Comment by swimmwatch** [comment]
@Lonami, it works. Thanks!
