### ISSUE TITLE
Invalid code. Please try again.Invalid code

### ISSUE THREAD

**Issue by londarks** [LonamiWebs/Telethon#3953]
Hello, I noticed that the telethon has a problem validating the access code that Telegram provides to it, after offering the code that Telegram offers, it returns me that it is invalid, I tried to look for an alternative but nothing worked

Basically I'm trying to make connections, with several Telegram accounts my code looks like this:

```
-> enter the credentials and start the client
-> pass the phone number in question to get the sms  -> await client.send_code_request(phone=phone_number)
-> then pass the code obtained  -> await client.start(phone=phone, polling=code) (modification to pass code directly)
error:  Invalid code. Please try again.Invalid code
```

I would like some help to solve this problem

**Comment by Lonami** [comment]
The "invalid code" error comes from Telegram when the call fails with one of these RPC errors:

https://github.com/LonamiWebs/Telethon/blob/346a3f0ef5652111c7bc167d4ccef5eb851c7901/telethon/client/auth.py#L217-L221

This means Telethon cannot "fix" this. It's Telegram saying the code is invalid. Because there is nothing for me to fix, I will close the issue. Unfortunately I can't really tell you why Telegram would say a (presumably) valid code is, in fact, not valid, because I have no idea why it would do that (beyond what's documented).
