### ISSUE TITLE
Very high latency in receiving the channel update to the bot from another channel

### ISSUE THREAD

**Issue by Slexyy** [LonamiWebs/Telethon#3965]
**Checklist**

* [x] The error is in the library's code, and not in my own.
* [x] I have searched for this issue before posting it and there isn't a duplicate.
* [x] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Code that causes the issue**
```python
from telethon import TelegramClient, events
...
client = TelegramClient(api_hash=api_hash, api_id=int(api_id), session='testbot')

@client.on(events.NewMessage(chats=channel_urls))
async def listener(event):
    message = event.message.message
    print(message)
    print(event.message.date)
```

The problem is, I read updates from another telegram channel and there is a lot of latency in receiving the message. I printed the telegram date and the local machine date and there was 9 seconds apart. From my own test channel, I receive the updates as soon as they're posted. I've made sure the clock is in sync on my test machine.

In my example, the telegram message was posted at 2022-10-30 16:00:32+00:00 and the ubuntu instance in London received it at Sunday, October 30, 2022 4:00:41.608 PM.

I even saw the messages in the channel on my phone telegram client before the ubuntu instance received it. Do you have any idea what could cause this latency and how to receive the messages as soon as they're posted with Telethon?

**Comment by Slexyy** [comment]
I saw that in your example you used from telethon.sync import TelegramClient, can this cause the high latency issue? In my code I just use from telethon import TelegramClient?

**Comment by Lonami** [comment]
I don't really know why this latency occurs. My best guess is Telegram decides to delay updates to clients which are not active (I don't know the exact definition for "active"), specially from large channels. As far as I remember, I have never experienced this myself. You can search previous GitHub issues for people with the same problem and further discussion.

`telethon.sync` should not introduce this form of latency at all.

I am pretty sure it's Telegram the one delaying the updates, not Telethon having some weird code that causes updates to be delayed. You can confirm this by adding a prints deeper inside the library to see when they occur and confirm if the delay is from Telegram or the library (if such print is instant but the event takes a long time after the problem is with the library, but as I say, I very much doubt this is the case; I have also heard other libraries having this issue).

**Comment by Slexyy** [comment]
Don't know if this is the right place to ask this question (but it's related to the original issue I had), is iter_messages() or get_messages() the best way to go through the latest message posted to a channel without such latency? It seems that in large public channels the new messages are distributed slowly to every subscriber to the websocket so I guess the best solution would be to call the channels latest message all the time? I might need some consultation help for this and am willing to pay for a complete solution :) The needed outcome is simple but I need to figure out the second best option for message scraping 👍

**Comment by Lonami** [comment]
Not at all. Any request will result in flood errors if used in quick succession.

The library doesn't use websockets, just plain sockets over TCP. Again, Telegram decides how to deliver updates, and what the client does or does not may influence this.
