### ISSUE TITLE
non-hexadecimal number found in fromhex()

### ISSUE THREAD

**Issue by jack-manual** [LonamiWebs/Telethon#3982]
Why haven't you fixed this bug after a long time?
Have you abandoned your telethon project?

error: non-hexadecimal number found in fromhex()
code:
```
   client = TelegramClient(
        session=path, 
        api_id=api_id, api_hash=api_hash, 
        connection=connection.ConnectionTcpMTProxyRandomizedIntermediate, 
        proxy=('20.208.129.34', 443, '7vQ1mpsyX_HR5QhN8OD3U3sgICAgICAgICAgICAgICA'),
    )
    client.connect()
```

**Comment by Lonami** [comment]
> Why haven't you fixed this bug after a long time?

I decide how to spend my time, and I haven't decided to work on this bug.

>  Have you abandoned your telethon project?

The project is not abandoned. You can see this for yourself. The last commit was just 3 days ago https://github.com/LonamiWebs/Telethon/commit/8ae75db86268a7726e16b100a93a2aca7643938d.

> error: non-hexadecimal number found in fromhex()

"Newer" proxies are not yet supported by the library. My stance on this hasn't changed since my comment in https://github.com/LonamiWebs/Telethon/issues/1319#issuecomment-1020057350:

> I have no intention to maintain MTProto proxy support, therefore, I'm closing this issue. If someone is interested in developing and maintaining MTProto proxies, please let me know or contact me, and we can work together so Telethon is able to provide the necessary abstractions for users to be able to plug proxy implementations from other projects.

If this feature is important to you, you're welcome to implement such a feature and send a PR so others can benefit from it as well.
