### ISSUE TITLE
get_message_history() does not work with limit=None

### ISSUE THREAD

**Issue by zhangyubaka** [LonamiWebs/Telethon#401]
In https://github.com/LonamiWebs/Telethon/blob/9a12738f0ed60f814c50bbc856032a20876f8d3b/telethon/telegram_client.py#L489
`limit = float('inf') if limit is None else int(limit)` converts limit into float, but in `tl/functions/messages.py`, python is still complaining argument needs to be an integer.
```python3
/usr/local/lib/python3.6/dist-packages/Telethon-0.15.3-py3.6.egg/telethon/tl/functions/messages.py in __bytes__(self)
   1739             b'\0\0\0\0' if self.offset_date is None else struct.pack('<I', int(self.offset_date.timestamp())),
   1740             struct.pack('<i', self.add_offset),
-> 1741             struct.pack('<i', self.limit),
   1742             struct.pack('<i', self.max_id),
   1743             struct.pack('<i', self.min_id),
error: required argument is not an integer
```
Sorry for my poor english.

**Comment by Lonami** [comment]
Pretty strange because `inf` shouldn't actually have been passed to the function:
https://github.com/LonamiWebs/Telethon/blob/9a12738f0ed60f814c50bbc856032a20876f8d3b/telethon/telegram_client.py#L503-L506

Operative system? Python version? Worked under my Linux box, 3.6.3. Can you try running this code I showed manually (`min(inf, 100)`)?

**Comment by zhangyubaka** [comment]
Running on Ubuntu 17.10, Python 3.6.
It appears to me that the package from PyPI is outdated. My problem is solved by install from github clone.

**Comment by Lonami** [comment]
Alright, yes, I haven't pushed this to PyPi.
