### ISSUE TITLE
UploadProfilePhotoRequest : RPCError 400: STICKER_MIME_INVALID (caused by UploadProfilePhotoRequest)

### ISSUE THREAD

**Issue by AtlantisDe** [LonamiWebs/Telethon#4039]
### UploadProfilePhotoRequest : RPCError 400: STICKER_MIME_INVALID (caused by UploadProfilePhotoRequest)

```python
https://tl.telethon.dev/methods/photos/upload_profile_photo.html

err version: Telethon 1.27.0
```

**Comment by newcoderforwhat** [comment]
I solved this problem by explicitly specifying UploadProfilePhotoRequest(file=file).
```
photo = "profile_photo.jpeg"
file = await client.upload_file(photo)
result = await client(UploadProfilePhotoRequest(file=file))
print(result.to_json())
```

**Comment by Lonami** [comment]
Probably because [`UploadProfilePhotoRequest`](https://tl.telethon.dev/methods/photos/upload_profile_photo.html) has gained a new optional parameter, `fallback`, which comes first, so the old code was no longer correctly setting the file.

As a reminder:

> You are using raw API, which means the results you are getting come directly from Telegram, and Telethon is not changing them in any way (other than adapting some input parameters where needed, all while respecting the intended values). Unfortunately this means it's something Telethon cannot "fix" and it's just the way Telegram's API works.

In this case, the raw API changed the order of parameters, which broke code not explicitly setting the file.

**Comment by Toster124** [comment]
client(UploadProfilePhotoRequest(fallback=True,
    file=client.upload_file(foto)
    ))
    
   
thats work for me
