### ISSUE TITLE
Implement support for async session

### ISSUE THREAD

**Issue by not-poma** [LonamiWebs/Telethon#4049]
As an asyncio library, telethon should use async for all I/O operations, including session calls that can access an external database. This ensures that all operations are performed efficiently and without blocking the main thread.

**Comment by Lonami** [comment]
This was planned for v2, doing so in v1 is a breaking change. Unfortunately v2 is not planned any time soon.

**Comment by not-poma** [comment]
Could be an extension. Telethon could check which abstract class the session inherits from and use the appropriate methods (sync/async).

**Comment by Lonami** [comment]
Telethon internals rely on the session being sync. Fixing that would likely affect the public API. It's no simple task, and I know because I attempted to do it before for v1. If you need this *now*, you can write your own session that does writes asynchronously, although reads will still need to be sync.
