### ISSUE TITLE
events.NewMessage Often misses messages from groups 

### ISSUE THREAD

**Issue by simbadmorehod** [LonamiWebs/Telethon#4055]
Using `@client.on(events.NewMessage(chats=chats))`

Users have noticed that the bot misses quite a few messages.

I don't know how to solve this problem, would be happy to get help or a temporary solution.

**Comment by Lonami** [comment]
Please follow the issue template next time.

You can install master with:

```
pip3 install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip
```

and configure `logging` with something like this:

```python
import logging
logging.basicConfig(format='[%(levelname) 5s/%(asctime)s] %(name)s: %(message)s', level=logging.WARNING)
logging.getLogger('telethon.messagebox').setLevel(logging.NOTSET + 1)
```

(You can configure it to your liking, but the `messagebox` level must be as low as possible. If you have multiple `TelegramClient`, please set a different `base_logger='name'` for each in their constructor).

This will print all updates being processed along with the current state of the `MessageBox` (which deals with the updates).

**This log will contain sensitive information**, so only share it with people you trust (or redact it before sharing it). You can [send it to me privately](https://t.me/Lonami) so that I and nobody else can analyze it (please link to this issue, so I know you're not spam).

This log should tell us if the updates are arriving and Telethon is ignoring them, or if Telegram is simply not sending the updates at all.

**Comment by simbadmorehod** [comment]
I did everything as you said, now should I wait for some time for the log to fill up? Generally, some messages come and some do not come, I'm just trying to figure out if Telegram can not send notifications of some messages deliberately.

**Comment by Lonami** [comment]
You should take a look to find if the "messages that don't come" (via Telethon event handlers) are in the log. Or if, when that happens, there are "gaps".

**Comment by simbadmorehod** [comment]
Unfortunately, I have a very large flow of messages and intercept those that do not come is an effort, but I understand the idea, I have previously added their own logging of some companies that I can track.

**Comment by simbadmorehod** [comment]
In theory, Telegram may not deliver some messages if I have 10+ accounts working in the client at the same time and they have 100+ groups each?

**Comment by simbadmorehod** [comment]
I send test messages to groups, everything intercepts, I can't catch what to repeat the problem.

As you suggested use `sudo journalctl -u bot.service | grep *message what is missing* `.

That would reveal the error, I'll be watching.

**Comment by simbadmorehod** [comment]
I think you should close the problem, because so far it is difficult to catch where the error was

**Comment by Lonami** [comment]
Okay, let me know if you encounter the issue in the future. Telethon should be detecting gaps in updates and recovering from those, so I was surprised to hear you were missing some. Unless Telegram is experiencing internal issues while that process occurred, of course.
