### ISSUE TITLE
Lookup an entity by its phone, but not by an id

### ISSUE THREAD

**Issue by aivel** [LonamiWebs/Telethon#412]
Hi there!

There is a bug in `_get_entity_from_string` method of `TelegramClient` class.
It is trying to lookup the entity from session by a phone number, when it is being kept under a `user_id` key:

<img width="936" alt="screen shot 2017-11-07 at 11 55 40 am" src="https://user-images.githubusercontent.com/3083784/32485166-7fcff2e4-c3b3-11e7-9973-f4862c02d433.png">

**Comment by Lonami** [comment]
Is the phone a string?

**Comment by aivel** [comment]
yep, prefixed with a `+` symbol

**Comment by Lonami** [comment]
Let me try on my end.

**Comment by Lonami** [comment]
Nice job, me:
https://github.com/LonamiWebs/Telethon/blob/83af705cc8fba30bf3f05d8a4c3ba243edc475ca/telethon/tl/entity_database.py#L128-L135

I bet you can see it too.

**Comment by Lonami** [comment]
Bear in mind you'll be returning all contacts every time you run the script (unless you call the function a second time in the same script), since the script doesn't save username/id to the `*.session` file. It would be good if once you got whoever you wanted, you printed it, and hardcoded its `InputUser`.

**Comment by Lonami** [comment]
https://pypi.python.org/pypi/Telethon/0.15.4.2

**Comment by aivel** [comment]
Greeat, thank you! 👍🏻
