### ISSUE TITLE
documentation is too complicated and lack of clarity

### ISSUE THREAD

**Issue by abdullzz** [LonamiWebs/Telethon#4187]
### Description

i really want to migrate from python-telegram-bot to this telethon, but the documentation is really lack of clarity, like how do i disable notification when sending messages for example?. the telethon use 'silent' keyword, very differs than the default naming convention on any other library.

### Checklist

- [X] This is a documentation problem, not a question or a bug report.
- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by abdullzz** [comment]
just got the answer from the group, turns out this library tightly use core method naming convention rather than the bot api one, like in other library

**Comment by Lonami** [comment]
> how do i disable notification when sending messages for example

[Telegram's API is huge](https://github.com/telegramdesktop/tdesktop/blob/d8f53d5f6096ad84177ff2ab3001ac918eed017b/Telegram/SourceFiles/mtproto/scheme/api.tl). The library does not offer friendly methods (i.e. methods bound to `TelegramClient`) for all you can do with Telegram's API. This is why the [raw API exists](https://docs.telethon.dev/en/stable/concepts/full-api.html).

It's a trade-off in how much I need to maintain with my limited time. Most commonly-used features get a proper method, with proper types, documentation and examples. Newer features are available if you need them, but you have to rely on the documentation elsewhere (often just the names).

> the telethon use 'silent' keyword, very differs than the default naming convention on any other library

For this particular example, [`silent` is the name Telegram's API uses](https://github.com/telegramdesktop/tdesktop/blob/d8f53d5f6096ad84177ff2ab3001ac918eed017b/Telegram/SourceFiles/mtproto/scheme/api.tl#L116). The HTTP bot API is not used as an inspiration. It's its own abstraction layer. I am not willing to spend time studying it to see how it maps with Telegram's API. Using its naming would probably make it more confusing for those using different MTProto libraries, or those reading the schema from Telegram's page directly.

> the documentation is really lack of clarity

> [telethon is the worst documentation among other telegram library](https://github.com/LonamiWebs/Telethon/issues/4166#issuecomment-1700712804)

Those are big words. I've spent a lot of effort writing a thorough guide and documented every method, with examples, for which there is a friendly variant (i.e. non-raw API). Raw API being documented is out of scope.

If you have concrete suggestions on how to improve it, let me know or send a pull requests, but as it stands, this issue is not actionable, so I will close it.

**Comment by abdullzz** [comment]
the learning curve for this library is really steep. i got lured to try this library because the documentation said that it will save some headache later, turns out its not for beginner like me since one must understand the prerequisite knowledge on understanding the core of telegram before migrating from other telegram library. and yeah the documentation is there for them whom already know what method to use. i cannot say that its the best documentation among other library either 🙏

**Comment by Lonami** [comment]
The basics should be simple by following the documentation in order. This should cover the majority of workflows (handling updates, sending messages, formatting, and such). Most methods in the client have examples. Functions beyond those can be used but are not documented.
