### ISSUE TITLE
More info on UpdateShortMessage in the docs and standard behaviour of message attribute in event.message.

### ISSUE THREAD

**Issue by hammersharkfish** [LonamiWebs/Telethon#4188]
### Describe your suggested feature

For this handler-
```
@client.on(events.NewMessage(chat_ids)) 
async def handler(event):
```
if the message comes from a channel it's wrapped in `UpdateNewChannelMessage ` but if it comes from a `bot `it get wrapped in `UpdateShortMessage ` . Please provide more info in the docs about `UpdateShortMessage ` . More importantly  the standard behavior of  `event.message` should be a `Message` object  but `UpdateShortMessage ` directly has the raw text . ie . event.message = Message() while listening to channels but while listening to bots it is `event.message = "Hello, directly raw text"` .

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
When using `events.NewMessage`, `event.message` should always be a `Message`, not an `Update`. If that's not the case, please open a bug report, not an enhancement suggestion.

The different update types used internally are an implementation detail which is in my opinion not worth documenting, so if that was all the issue was asking, then I'll be closing.
