### ISSUE TITLE
Piping file data to http response is very slow

### ISSUE THREAD

**Issue by divyam234** [LonamiWebs/Telethon#4197]
### Code that causes the issue

I have observed when piping file response directly to request is very slow even if the bandwidth is higher it seems it's capped to 1MB/s . For example If I stream 4k then it buffers a lot.I have done some implementation in pyrogram it's very fast there I can stream 4k videos easily without buffering.But could the reason I reckon both libs are using same crypto implementation.

### Expected behavior

No buffering during streaming 

### Actual behavior

Buffering during streams

### Telethon version

1.30

### Python version

3.10

### Operating system (including distribution name and version)

Ubuntu 22.04

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
Nothing in Telethon is intentionally limiting the bandwidth.

I'm personally not interested in this "who is faster" battle so I will be closing the issue.

But I have occasionally seen attempts from other people to improve the transfer speeds with great success (sadly, I don't have the link of any at hand. It was a long time ago).

I'm sure you can find something by searching online. Otherwise, it comes down to creating multiple tasks per file part request. And perhaps changing up what `aes.py` uses underneath. Though from my tests, `cryptg` is already plenty fast.
