### ISSUE TITLE
Upload to specific topic in Telegram groups

### ISSUE THREAD

**Issue by tmxkwpn** [LonamiWebs/Telethon#4276]
### Describe your suggested feature

I would like to upload to specific topics inside a supergroup, instead of uploading to the general topic.

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
There are no plans for this in v1. You can use the requests from https://tl.telethon.dev if you really need to.

**Comment by GenocideStomper** [comment]
> There are no plans for this in v1. 

Are there plans for this in v2, and is there a roadmap for v2?


> You can use the requests from https://tl.telethon.dev if you really need to.

I don't understand what I'm looking at here 😅

**Comment by Lonami** [comment]
> Are there plans for this in v2

v2 is a lot cleaner because it enforces strict type-checking, so it is a lot easier to add and maintain new fields, yes.

> is there a roadmap for v2?

No, I do not know when I will consider it "ready".

> I don't understand what I'm looking at here

https://docs.telethon.dev/en/stable/concepts/full-api.html. Or you can modify the library's source to add what's missing for your own needs.
