### ISSUE TITLE
Add string variants of file_id and file_unique_id

### ISSUE THREAD

**Issue by FreeM1ne** [LonamiWebs/Telethon#4311]
### Describe your suggested feature

Add string variants of file_id and file_unique_id
file_unique_id=AgAD-wsAArOYgFY
file_id=BQACAgUAAxkBAAIBcGXQXOrE7HXwaG1vfDWhFZkGykO4AA

### Checklist

- [X] I have searched for this issue before posting it and there isn't a duplicate.

**Comment by Lonami** [comment]
I do not plan to maintain file_ids. I plan to remove them entirely in v2.

**Comment by FreeM1ne** [comment]
Are they currently supported?
Why did you make such a decision? Because many other libraries use the file_id and file_unique_id system e.g. aiogram

**Comment by Lonami** [comment]
`file_id` is a custom format invented by the HTTP bot API. Telethon speaks with Telegram's servers directly via MTProto.

Supporting `file_id` in Telethon would mean either reverse engineering them (as they're just base64-encoded bytes) or finding out somewhere that has done so already.

It was done once. The format changed. I haven't updated it since. So they're effectively broken.

I no longer have any interest in keeping up with that format, and noone else has sent a PR (with correct licensing) fixing their support.
