### ISSUE TITLE
How can I set specific admin rights of channel to the user?

### ISSUE THREAD

**Issue by User195** [LonamiWebs/Telethon#442]
I used your dos site https://lonamiwebs.github.io/Telethon and I foud only EditChatAdminRequest method that require only chat_id, user_id, is_admin (bool) but is admin how can I set specific rights (like users to channel, edit description, add new posts etc). I really tried to look for your docs but with no luck

**Comment by User195** [comment]
Hm, perhubs I found the method
EditAdminRequest

**Comment by Lonami** [comment]
Chats hardly have any admin options, you're probably looking for megagroups. So [`EditAdminRequest`](https://lonamiwebs.github.io/Telethon/methods/channels/edit_admin.html) should be what you need. This question is done right because you've clearly stated you have tried looking for it, and while you were close wasn't quite there :)

**Comment by Lonami** [comment]
Yeah I was typing that then your comment came. Closing issue.
