### ISSUE TITLE
The confirmation code has expired

### ISSUE THREAD

**Issue by Maverick1983** [LonamiWebs/Telethon#4424]
### Code that causes the issue

sign_in

### Expected behavior

Log in to Telegram account

### Actual behavior

return this error: The confirmation code has expired (caused by SignInRequest)

### Telethon version

1.36

### Python version

3.9.13

### Operating system (including distribution name and version)

Windows 11 x64

### Checklist

- [X] The error is in the library's code, and not in my own.
- [X] I have searched for this issue before posting it and there isn't an open duplicate.
- [X] I ran `pip install -U https://github.com/LonamiWebs/Telethon/archive/v1.zip` and triggered the bug in the latest version.

**Comment by Lonami** [comment]
#3039, #799.

**Comment by Zero-Trust-Tea** [comment]
Hey guy's, did someone know if there is a telethon bot where you can send a phone number to Telegram bot and then it will request at the bot interface a code like message and if required a verefication password, so the point is that the authentication by sending phone number, code, and verefication password if required will be happening through the bot interface and not like it by default set by telethon through input in console. If someone knows or can make such like that I will so appreciate it.

**Comment by Zero-Trust-Tea** [comment]
Because my problem is that I was trying to do that, and my problem is when I sending code to the bot, it responding that the verification code has expired when I just send it, only working if I authorize throw the console in pycharm and entering credentials there without using telegram bot, btw I want to create that functionality in bot, can someone help
