### ISSUE TITLE
Sudden LocationInvalidError

### ISSUE THREAD

**Issue by ingria** [LonamiWebs/Telethon#500]
I'm downloading the file like this:

```python
photo_location = channel.photo.photo_big

input_file = InputFileLocation(
    volume_id=photo_location.volume_id,
    local_id=photo_location.local_id,
    secret=photo_location.secret
)

file_location = os.path.join('/tmp', 'photo{}.jpg'.format(channel.id))

self.client.download_file(input_file, file_location)
```

And suddenly this error started to happen:

> LocationInvalidError(...), 'The location given for a file was invalid. See https://core.telegram.org/api/files#downloading-files')

I'm experiencing it on every of couple dozens of clients on this only channel: `@ShavkatMirziyoyev`. Any ideas why?

**Comment by Lonami** [comment]
`photo_small` works for some reason.

**Comment by delivrance** [comment]
Probably this is failing due to some internal issues at Telegram itself because even the Android app isn't able to download that (as said by Lonami).

Anyway, here's a workaround: Instead of getting the photo location's info (volume_id, local_id, secret) by using `contacts.ResolveUsername` alone (or whatever you used), use the info obtained by calling `channels.GetFullChannel`. The actual difference is just the volume_id being 238225099 instead of 238225020

**Comment by Lonami** [comment]
@delivrance thanks!

**Comment by delivrance** [comment]
As a side note: my guess is that the android app is using `contacts.ResolveUsername` alone to get the photos, this is why is not working, and tdesktop is getting the proper info with `channels.GetFullChannel`.
