### ISSUE TITLE
Error after trying to download a file from another DC

### ISSUE THREAD

**Issue by CrocutaCrocuta** [LonamiWebs/Telethon#53]
Hi!
When I attempt to download a media from another DC, rather than on which I logged in, I get an error
`Read RPC error: (RPCError(...), 'The file to be accessed is currently stored in a different data center (#X).')`
and after an error
`Read RPC error: (RPCError(...), 'The key is not registered in the system.')`
After which the data no longer come. When i restart and use the session file, the same error occurs about the not registered key. It only helps to delete the session file.

**Comment by Lonami** [comment]
What version are you using? It should now be possible to work with different datacenters.

> `Read RPC error: (RPCError(...), 'The key is not registered in the system.')`

I'm aware of this, it's like if the `*.session` file is corrupted after receiving errors on login, it's a bit like #7. Session file gets corrupted.

**Comment by CrocutaCrocuta** [comment]
I use 0.8 version installed via pip.

**Comment by Lonami** [comment]
I wonder if it has something to do with:
> The problem is because wrong timezone or clock settings on my operating system

As [@realbardia mentioned](https://github.com/Aseman-Land/Cutegram/issues/56#issuecomment-106784859). Maybe some request is re-sent but the time has changed too much by then? Though, this was not the (only) issue.

It seems like they fixed it by adding [these lines](https://github.com/Aseman-Land/Cutegram/blob/3647f28720ed08ad6eabef530d65c5e1a83d4fc6/Cutegram/main.cpp#L52-L54) (it took me a while to find a commit [close](https://github.com/Aseman-Land/Cutegram/commits/master?after=e48981203f23a935a7b59952ebbeada5a2ec2f9d+244) to the date the issue was fixed!), but I [already handle DC switching](https://github.com/LonamiWebs/Telethon/blob/fbc7aabf1396abfb2fca4092063b2c3a9c14e501/telethon/telegram_client.py#L183), so I'm not sure what the issue can be.

[Other people](https://github.com/vysheng/tg/issues/725) with this issue solved it by deleting the [`.telegram-cli`](https://github.com/vysheng/tg/issues/725#issuecomment-130002015) folder, which is the equivalent to deleting the `*.session` file for Telethon. But… that should not be the right way to fix the problem.

Maybe a longer log could provide some more insight. Not sure.

**Comment by Lonami** [comment]
I reproduced the bug, [here is the log](https://gist.github.com/Lonami/477a918b7bba83f6ea7a60dab14566b5). Note this [line](https://gist.github.com/Lonami/477a918b7bba83f6ea7a60dab14566b5#file-crash-log-L21) though, for some reason I seem to be creating a new session for which I don't have the key registered.

**Comment by edmilsonrobson** [comment]
I'm having the same issue. Any workarounds, @Lonami ?

**Comment by Lonami** [comment]
> Any workarounds

Nope, I'm still clueless. I'm not sure how we can handle this, and all help is appreciated.

**Comment by edmilsonrobson** [comment]
Any way to maybe manually connect to the correct DC before downloading the file? I'm kinda new to the Telegram API, so I don't know if that's a possibility.

**Comment by Lonami** [comment]
> Any way to maybe manually connect to the correct DC before downloading the file?

No, not *before* downloading the file but at the beginning, possible by changing [this line](https://github.com/LonamiWebs/Telethon/blob/master/telethon/tl/session.py#L13). However, it will reconnect you as soon as a `InvalidDCError` happens, so you would have to change more things.

**Comment by edmilsonrobson** [comment]
I see. I noticed that the error is triggered by using invoke() for this [GetFileRequest](https://github.com/LonamiWebs/Telethon/blob/fbc7aabf1396abfb2fca4092063b2c3a9c14e501/telethon/telegram_client.py#L706), and inside invoke() it tries to reconnect to another DC because of the error. Isn't triggering that sudden reconnect in the middle of the execution the cause of this problem?

Shouldn't this reconnection be made more safely before invoking the GetFileRequest by using the [dc_id parameter](https://core.telegram.org/api/datacenter) of the file or something?

I'm not sure if it's necessary to reconnect or if it's possible to create a second connection just to download the file, as I'm new to the whole Telegram API, but just my 2 cents.

**Comment by Lonami** [comment]
> or if it's possible to create a second connection just to download the file

This is the way it should be done, but I have no clue on how I could possibly stabilish two connections at once.

> Shouldn't this reconnection be made more safely before invoking the GetFileRequest by using the dc_id parameter of the file or something?

It indeed looks like a good possibility, because that parameter [hasn't gone away](https://lonamiwebs.github.io/Telethon/constructors/file_location.html) and it should be possible to access it (not sure yet, can't test at the moment). But still, reconnection should be handled gracefully: disconnect, change address, and reconnect; not sure how this causes a `The key is not registered in the system.` error.

> Isn't triggering that sudden reconnect in the middle of the execution the cause of this problem?

Again, I think it should be handled gracefully, but maybe you're right and it happens, not on the `.receive()` part but on the `.send()` one.

**Comment by Lonami** [comment]
After some more attempts, I noticed that I received:
```
[09:53:34.758/MainThread] DEBUG: Handling update for object new_session_created#9ec20908 first_msg_id:long unique_id:long server_salt:long = NewSession
```

When trying to `.receive()` the `InvokeWithLayerRequest` (sent on reconnection) after the first error (Invalid DC). Until now, I had been ignoring these, but I decided to add another handler:
```python
    def handle_new_session_created(self, msg_id, sequence, reader):
        Log.i('Handling new session created')
        result = reader.tgread_object()
        self.session.salt = result.server_salt

        return True
```

Called from `process_msg`, `if code == 0x9ec20908`. However, this changed nothing. I still receive the `RPCError`of `AUTH_KEY_UNREGISTERED`.

Now I'm trying to connect, but for some reason, I'm getting `OverflowError: can't convert negative int to unsigned` when I do send the `(auth.sendCode (ID: 0x86aef0ec) = (allow_flashcall=None, phone_number=+34xxxxxxxxx, current_number=None, api_id=xxxxx, api_hash=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx))`. And it's strange, because I touched nothing there.

**Comment by Ak4zh** [comment]
Is it solved?

I get

`telethon.errors.rpc_error_list.FloodWaitError: (FloodWaitError(...), 'A wait of 83184 seconds is required')`

Everytime I try to login, and after 4-5 attempts I get FloodWait Error, I am trying since last 3 days, same code works fine for other telegram account.

This error always occur on one specific account.

I also tried deleting .session file.
I am usin the latest version of telethon

**Comment by Lonami** [comment]
> Everytime I try to login, and after 4-5 attempts I get FloodWait Error, I am trying since last 3 days, same code works fine for other telegram account.

That error is per phone so deleting your session won't have any effect. Be careful about the requests you make and wait patiently.

**Comment by Ak4zh** [comment]
Sorry, I pasted wrong error.
I am asking about the `AuthKeyUnreisteredError`
