### ISSUE TITLE
Strange issue with updates regarding private channels

### ISSUE THREAD

**Issue by samsebree** [LonamiWebs/Telethon#534]
Hi there!

I have read the documentation, and unfortunately I haven't been able to resolve a strange issue I am having.

I currently have an update handler that is able to successfully interpret updates for all individual messages and group messages.

However, some channels seem to trigger the update handler, whereas other channels do not.

I have created a test private channel on another account and added my original telethon enabled account to the channel. When I send messages in this channel it triggers the update handler just fine.

However, my account is already in another private channel (one I did not create). Whenever a message is sent in this private channel, it does not trigger the update handler.

My code is basically straight from the telethon examples:

```
def main():
   *standard example code here*

    client.add_update_handler(update_handler)
    input('Press Enter to stop the handler\n')

def update_handler(update):
    print(update.stringify())
    fh = open("chatHistory.txt", "a")
    fh.writelines(update.stringify() + "\n")
```

I've made sure that the channel isn't muted or anything like that. Any help would be much appreciated.

**Comment by Lonami** [comment]
Thanks, this issue is well written and there's nothing wrong with it. However, this seems related to #237 so I will close this to keep the issues section free of noise. Basically (and as a simple guess), calling `updates.getDifference` through [this request](https://lonamiwebs.github.io/Telethon/methods/updates/get_difference.html) *might* work, if you would like to help. There's still work to be done regarding updates, sorry.
