### ISSUE TITLE
send_message return

### ISSUE THREAD

**Issue by heoh** [LonamiWebs/Telethon#547]
method send_file returns None but docstring is:
`        Returns:
            The message (or messages) containing the sent file.`
send_message returns message object, but send_file isnt

**Comment by Lonami** [comment]
If you pass multiple files:
https://github.com/LonamiWebs/Telethon/blob/fde0d60f726df8f7887c9fb83f3b532effa2164d/telethon/telegram_client.py#L879-L893

Otherwise:
https://github.com/LonamiWebs/Telethon/blob/fde0d60f726df8f7887c9fb83f3b532effa2164d/telethon/telegram_client.py#L954-L966

So it's probably `._get_response_message` failing. How does the method call look like?

**Comment by heoh** [comment]
`self.download_media(message, file_name)
            if message.media.caption:
                if reply_id:
                    sent_message = self.send_file(chat_id, file_name, caption=message.media.caption, reply_to=reply_id)`

**Comment by Lonami** [comment]
I doubt the file has been downloaded that fast. Files with size 0 can't be sent and thus returns `None` message.

**Comment by Lonami** [comment]
Actually, it should `raise FilePartsInvalidError`.

**Comment by heoh** [comment]
The file is sent, but method returns None.
2.3mb video for example

**Comment by Lonami** [comment]
Right. Forgot `.download_media` is blocking.

**Comment by heoh** [comment]
I need id from message object. Now i using that:
```
self.send_file(chat_id, file_name)
id = self.send_message(chat_id, 'id').id
self.delete_messages(chat_id, [my_id])
id -=1
```
but it is ugly looking crutch

**Comment by Lonami** [comment]
Not sure what version you're using. Upgrade to the latest version, and if you can reproduce consistently with some small code I want use to trigger the bug too reopen.
