### ISSUE TITLE
FloodErrors: And how to avoid them

### ISSUE THREAD

**Issue by OpaDopa** [LonamiWebs/Telethon#557]
Hello Guys,

Is there a telethon flood guideline? So many requests per second or something? A Random method or? 
Or first error on 112s second on 320s etc..

Like to know how many requests per minute / hour? 

Greetingsss

**Comment by Lonami** [comment]
Nothing official no. The best you can do is time how many can you do as fast as possible and print that number, how long it took, and how long the flood wait is. I'm sure spammers would be helpful if you were to make a guide for everyone because this shouldn't affect a normal usage.

**Comment by Mardoqueu-Pimentel** [comment]
@OpaDopa Hello! Did you get any info about the limits? I need to do a stress test where I simulate a great number of people sending messages in a group for my bot to process. Since I haven't found a way yet, I tried to send messages using my account, but even putting a delay of 1 sec, I got a time ban.
