### ISSUE TITLE
"Make sure you have encountered this peer before" - client.get_input_entity

### ISSUE THREAD

**Issue by limun-dnaw** [LonamiWebs/Telethon#584]
I'm getting this error:
`in get_input_entity 'Make sure you have encountered this peer before.'.format(peer) `

Is there a way to force the library to see the given peer? In my case it's a private announcement channel which I'm not an admin of. 
```
# Not found, look in the latest dialogs.
# This is useful if for instance someone just sent a message but
# the updates didn't specify who, as this person or chat should
# be in the latest dialogs.
```
Or the only way is to wait for it to get in my latest dialogs?

**Comment by Lonami** [comment]
You can see a peer in many ways:
- Telegram sends you `Updates` with information about them.
- It's in your dialogs, and you have got them at least once.
- It's in a group, and you have retrieved its participants.
- You find them via username or global search.
- You find them when getting the history (or a single message) since Telegram also shows adds the users there.

Regarding the first point, I don't know how Telegram decides whether to send you or not the user. Regarding the last, it's probably the best if you're working with updates and a call to get (input) entity fails.

In any case the library caches every seen user for convenience and by default. But no, you can't "force" ID, you need their hash somehow.
