### ISSUE TITLE
Error: Can't decode packet (b'S\xfe\xff\xff')

### ISSUE THREAD

**Issue by olivier-nexmo** [LonamiWebs/Telethon#609]
Hi,

I have a script that runs all the time (While true:), with a pause of 5 minutes every loop to avoid flooding, getting the messages from a Telegram channel.

From time to time, I can see the error:

2018-02-14 20:22:26
Error: Can't decode packet (b'S\xfe\xff\xff')
2018-02-14 20:27:26
Error: Can't decode packet (b'S\xfe\xff\xff')
2018-02-14 20:32:26
2018-02-14 20:37:26
2018-02-14 20:42:26
2018-02-14 20:47:26
2018-02-14 20:52:27
Error: Can't decode packet (b'S\xfe\xff\xff')
2018-02-14 20:57:27
Error: Can't decode packet (b'S\xfe\xff\xff')
2018-02-14 21:02:27
2018-02-14 21:07:27
2018-02-14 21:12:27
2018-02-14 21:17:27
2018-02-14 21:22:27
2018-02-14 21:27:28
Error: Can't decode packet (b'S\xfe\xff\xff')
2018-02-14 21:32:28

I've seen it reported before but the bugs were closed.

What is causing the issue?

Thank you

**Comment by Lonami** [comment]
> I've seen it reported before

No, this bug hasn't been reported here before. You're probably referring to #7, but that's slightly different. Notice that `b'l\xfe\xff\xff'` is `-404` while yours, `b'S\xfe\xff\xff'`, is `-429` (or "too many requests" as HTTP error code). Are you using a proxy or something?

**Comment by olivier-nexmo** [comment]
Ok, thank you.
No, I'm not using a proxy. Neither a VPN. Just running on my computer at home.
Is there a limit on Telegram API as how many calls we can make per hour? or per day? Which will trigger the HTTP too many requests error?

**Comment by Lonami** [comment]
I have no idea why Telegram sometimes replies with negative HTTP error codes but other times it replies with proper RPC errors (in this case, I presume, it should raise a `FloodWaitError`, but instead it's literally returning a negative integer as a response). Neither I know what I should do in this case. Reconnect, like I do with `-404`? Treat is like `FloodWaitError` and raise that? I don't know if you can invoke things after this error since I've never encountered it. It seems that you can except it and pretty much ignore it from your log… The library could just retry?

**Comment by Lonami** [comment]
It has been a while, please reopen if it still happens in the latest version. If it does, also provide a `DEBUG` log like so:
```python
import logging
logging.basicConfig(level=logging.DEBUG)
...
```
