### ISSUE TITLE
How to get channel info from forward header

### ISSUE THREAD

**Issue by gtavasoli** [LonamiWebs/Telethon#63]
Hi... when u get a message for example by GetHistoryRequest if the message has fwd_from (type: **MessageFwdHeader**) it has only from_id, channel_id, channel_post, and date. how can I get forward peer type and channel or user info only by id?

**Comment by Lonami** [comment]
Try constructing an `InputChannel` with only the ID, and set the `access_hash` to 0, or -1, for testing purposes. I'm not sure if it has to be this way, but it's my first guess.

**Comment by gtavasoli** [comment]
Unfortunately, this solution did not work. :(

**Comment by Lonami** [comment]
I tried looking for [`MTPMessageFwdHeader`](https://github.com/telegramdesktop/tdesktop/blob/297856db32856295d65c6e52943104b2d2b5fe01/Telegram/SourceFiles/mainwidget.cpp#L4319) on the official client and I can't see the use of a hash anywhere. [`peerFromChannel`](https://github.com/telegramdesktop/tdesktop/blob/e8a3535c74e9becef0d21fae48ec81b4e0c560d8/Telegram/SourceFiles/structs.h#L86-L88) is also a strange cast (not sure why it has to do that), which in Python would be something like `0x200000000 | (id & 0xFFFFFFFF)`. And then [`channelLoaded`](https://github.com/telegramdesktop/tdesktop/blob/59636ac0724b39427bdfdf934611b0ee982cbbbf/Telegram/SourceFiles/app.h#L137-L139) uses [`PeerData::FullLoaded`](https://github.com/telegramdesktop/tdesktop/blob/e8a3535c74e9becef0d21fae48ec81b4e0c560d8/Telegram/SourceFiles/structs.h#L334)… Which I'm not sure how it works. Sorry I'm clueless.

**Comment by pazis** [comment]
I have the same issue with super groups...

I want to send a message to a super group I'm already a participant. I have saved the `chat_id` but I don't have the `access_hash` to make an `InputPeerChannel`.

For channels, I can re-resolve the username to get the `access_hash`, but how about super groups? Most probably the `/joinchat/XXXXXXXX` link has expired already, and I have not stored the `access_hash`. 

Any possible way to find `access_hash`?

**Comment by Lonami** [comment]
>I have the same issue with super groups.

Those are a different story though, because a forwarded message belongs to an *user* and not the *group* itself. If you are a participant, you **should** be able to find it through `.get_dialogs()`.

**Comment by Lonami** [comment]
Shoot, you mentioned you had the chat ID only and not the hash. And [this method](https://lonamiwebs.github.io/Telethon/methods/messages/get_full_chat.html) mentioned on #64 works exactly in that way: only requires an ID.

**Comment by pazis** [comment]
@Lonami thanks a lot. `.get_dialogs()` should work. `get_full_chat` though is only for groups I think. Doesn't work for super groups. ❤️

**Comment by Lonami** [comment]
> `get_full_chat` though is only for groups I think.

I wonder, though, if one could use its equivalent for channels and pass `0` as `access_hash`. Maybe that way it would resolve the full channel. I don't know.

**Comment by Lonami** [comment]
```python
result = self.invoke(GetFullChatRequest(fwd.channel_id))  # CHAT_ID_INVALID
result = self.invoke(GetFullChannelRequest(InputChannel(fwd.channel_id, 0)))  # CHANNEL_INVALID
```

¯\\\_(ツ)\_/¯

**Comment by Lonami** [comment]
One second. I just realized something. If you retrieve some [messages](https://lonamiwebs.github.io/Telethon/types/messages/messages.html), say for instance [`MessagesSlice`](https://lonamiwebs.github.io/Telethon/constructors/messages/messages_slice.html) which is the most common (or [`Messages`](https://lonamiwebs.github.io/Telethon/constructors/messages/messages.html), both have the attributes we're interested in), you can see how they both have a `chats` and `users` member. You have to look for the channel under those `chats`, because a [`Channel`](https://lonamiwebs.github.io/Telethon/constructors/channel.html) is a [`Chat`](https://lonamiwebs.github.io/Telethon/types/chat.html).

So say you have the ID for the channel you want. To get the channel itself, you would do something similar to (I haven't tested):
```python
channel = next(c for c in messages.chats if c.id == channel_id)
```

Now you have the channel + the access hash, so it should work. Closing this issue. Another friend just asked me so I realized it could be done this way. Sorry for the delay.

**Comment by orkenstein** [comment]
@pazis, so were you able to retrieve `access_code` for the channel?

**Comment by Lonami** [comment]
https://github.com/LonamiWebs/Telethon/wiki/Retrieving-an-entity#via-messagefwdheader

**Comment by Lonami** [comment]
Actually you should probably be able to `client.get_entity(fwd.from_id)` or `client.get_entity(PeerChannel(fwd.channel_id))`.
