### ISSUE TITLE
List of groups

### ISSUE THREAD

**Issue by chri1389** [LonamiWebs/Telethon#653]
Hello.
After I have connected a client, How can I receive a list of only the groups that the user is subscripted? 
-group id, list of users in this group, group name

Thank you very much!

**Comment by Lonami** [comment]
Sounds like your job.

**Comment by Lonami** [comment]
There's a method called `.get_dialogs()`. You're responsible for doing `isinstance(dialog.entity, Chat)` yourself.

**Comment by chri1389** [comment]
Thank you, but with this method I can see the list of the last chat (for example the last ten chat etc..).
But if it's been a long time from the last message in a specific group, this method doesn't return the group data's..
I need to see all the groups of the user and what users are in every group.

Is there a method to do this?

Thank you!

**Comment by Lonami** [comment]
Read the manual.

**Comment by marcoskichel** [comment]
Wow, rude!

**Comment by Lonami** [comment]
The issues section is for **bugs with the library**, not to ask for help. Nowhere I insulted the original author, I only told them to read the documentation. I spent many hours writing that so it could be read instead of asking. If someone's going to ask, they should at least do it in the right places.
