### ISSUE TITLE
telethon.tl.types.Message is unhashable after upgraded to 0.17+

### ISSUE THREAD

**Issue by sammyhk** [LonamiWebs/Telethon#655]
After upgrade from 0.16.2.x to 0.17+, our App broken due to `telethon.tl.types.Message` become unhashable.
Following is a simple test case to reproduce this issue:
```py
from telethon.tl.types import Message

print('Message.__hash__:', Message.__hash__)
msg = Message(1, None, None, 'Testing 1')
testSet = set([msg])
testSet |= set([msg])
print('testSet: ', testSet)
```

Output from 0.16.2.3:
```sh
telethon-0.16.2.3>pip3 install telethon==0.16.2.3
telethon-0.16.2.3>test_case.py
Message.__hash__: <slot wrapper '__hash__' of 'object' objects>
testSet:  {<telethon.tl.types.Message object at 0x017B0BF0>}
```

Output from 0.17.4.5:
```sh
telethon-0.16.2.3>pip3 install telethon==0.17.4.5
telethon-0.17.4.5>test_case.py
Message.__hash__: None
Traceback (most recent call last):
  File "...\test_case.py", line 5, in <module>
    testSet = set([msg])
TypeError: unhashable type: 'Message'
```

**Comment by Lonami** [comment]
I was unaware TLObjects ever were hashable. You can `hash(obj.to_dict())` instead. Or make a `dict` by `{msg.id: msg}`.

**Comment by Lonami** [comment]
After running `git bisect` seems like the faulty commit is fbd53e2126f8f46a86ed3bee824817a3dad793af.

**Comment by Lonami** [comment]
Not sure if your app was working properly or why you had the need to hash type. Apparently if you override `__eq__`, you also must override `__hash__` (see "[Types that define `__eq__` are unhashable?](https://stackoverflow.com/a/1608882/4759433)"). Also, the `__hash__` default implementation seems to rely on the ID of the object, so your code should never show that two items were the same as new objects are always created (thus in likely different memory locations), as mentioned in "[What is the default \_\_hash\_\_ in python?](https://stackoverflow.com/q/11324271/4759433)".

Since `__hash__` is supposed to be fast (I guess?) I'm not going to implement this on the library because it's rather costly. You can however do the following:
```python
from telethon.tl import TLObject


def my_hash(self):
    d = self.to_dict()
    return hash(tuple(tuple(v) if isinstance(v, list) else v
                      for k, v in sorted(d.items(), key=lambda kv: kv[0])))


TLObject.__hash__ = my_hash
```

Then all TLObjects (including `Message`) should be hashable, but it might be slow if the object has a lot of other nested objects or long lists (which are not hashable and need to be a tuple).

**Comment by sammyhk** [comment]
Yes, our code only rely on the equality of the same object instance. Our app use Command Pattern to delegate the message processing logic to different commands and consolidate the processed messages using set union operation, something like the following code:
```python
class Command(Interface):
	"""Execute the command on selected messages, return the list of processed messages"""
	def execute(self, messages):
		pass


class Invoker:
	# commands initialize in constructor...
	_commands = []

	def process(self, messages):
		processed_messages = set()
		for command in self._commands:
			processed_messages |= set(command.execute(messages))
		# do work on processed_messages...
```

Before commit of fbd53e2, TLObject does not override `__eq__` so python using default implementation of `__eq__` and `__hash__` which only check the equality of same object instance in python runtime.
After commit of fbd53e2 which only override `__eq__` but not overriding `__hash__` causing this issue happened.

**Comment by Lonami** [comment]
Your solution then is `{id(obj): obj}` and `.update()` it.
