### ISSUE TITLE
Implement method to catch up on updates while the script was offline

### ISSUE THREAD

**Issue by gsahbi** [LonamiWebs/Telethon#746]
If sb sends a message when the client was offline, it's not received as an update when I reconnect.
Is there a workaround ?

**Comment by Lonami** [comment]
@JosXa was working on something but he's somewhat busy. Basically you need to call `client(GetDifferenceRequest(...))` with the previous known state. If you were to make a pull request for it, it would be nice :)

**Comment by gsahbi** [comment]
Ok, as I’m still new to this code what do you think of this strategy; for each incoming eveny or message we save the state into session ; we need to add another column
Then upon restart and before entering the polling loop we  call GetDifferenceRequest and for each update received we fire the event handler

I’m still not sure how to tackle this, I need some time to understand the whole thing. Maybe you can share some thoughts to help me out

**Comment by Lonami** [comment]
Exactly. We need to persist the previously known update state if we want to fetch those while we were offline. You basically said it all (save the state to the database, maybe only on disconnect, perhaps on every change, see [`update_state.py`](https://github.com/LonamiWebs/Telethon/blob/master/telethon/update_state.py).

Do note that I don't want this to be a default. Instead, if you're going to work on it, make a `.catch_up()` method or similar so that it passes all the updates through the handlers mechanism. So normal workflow would be start, catch up, idle.

**Comment by Lonami** [comment]
https://github.com/LonamiWebs/Telethon/commit/37436bdeee6ee86f9aea66c340deb50c1c093234 is a start. Further enhancements are welcome.
