### ISSUE TITLE
Already saved entities are broken after manually deleting auth_key in session file

### ISSUE THREAD

**Issue by Yerofeev** [LonamiWebs/Telethon#754]
Hello,
thanks for your library!

* Description: 
I launched Telethon client using the same session file on 2 machines, got AUTH_KEY_DUPLICATED. After having manually removed auth_key with:
```
client.session.auth_key = None
```
and reconnecting & restarting the client, GetHistoryRequest returns  'Invalid channel object' error for channels, saved in this session.
```
m = client(GetHistoryRequest(peer=channel, limit=30, offset_date=None, offset_id=0, min_id=0, max_id=0, add_offset=0, hash=0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/Telethon-0.18.2-py3.5.egg/telethon/telegram_bare_client.py", line 459, in __call__
  File "/usr/local/lib/python3.5/dist-packages/Telethon-0.18.2-py3.5.egg/telethon/telegram_bare_client.py", line 551, in _invoke
telethon.errors.rpc_error_list.ChannelInvalidError: Invalid channel object. Make sure to pass the right types, for instance making sure that the request is designed for channels or otherwise look for a different one more suited
>>> channel
<telethon.tl.types.InputPeerChannel object at 0x7eff5a634b38>
```
For channel's names that were not solved in this session, everything is fine.
* OS: Ubuntu 16.04
* Python 3.5
* Telethon version 0.18.01/0.18.02

Not sure whether I should have manually deleted auth_key, anyway had been thoroughly searching but did not find solution: is it bug or expected behavior and now I should save resolved entities in new sesison file again?

**Comment by Lonami** [comment]
The `access_hash` is probably invalid for that new session (not sure though). You can manually delete the entities from the SQLite table they belong so you will force yourself to find a new hash. It's an error returned by the API like I said possibly because you did that weird thing with session files around. You can move the session file but you shouldn't copy it, just make a new one.

**Comment by Kyle2142** [comment]
A single session can be copied and used simultaneously:
![screenshot_20180410-155005](https://user-images.githubusercontent.com/19349418/38560885-355bf0dc-3cc6-11e8-8f34-ed18a12daaa1.png)
(Note: __client__ package is just a script I made to abstract the login code)

**Comment by Yerofeev** [comment]
Ok, thanks.

**Comment by Lonami** [comment]
See #777 for more on `AUTH_KEY_DUPLICATED`.

**Comment by weibeld** [comment]
@Kyle2142 is it ok to copy a session file where the user is already logged in, and using it with a new TelegramClient, so that the new TelegramClient is also already logged in?

It seems to work in my initial tests, but I don't know if there could be any issues if it is scaled up.

In particular, I want to dynamically launch Telethon processes, each running a TelegramClient receiving updates for a specific chat. But I want the user to do the login procedure (i.e. receiving and entering login code) just once at the beginning. So, I thought about creating an initial session file to log the user in, and then using a copy of this session file for each new Telethon process. Do you see any problems with this?

**Comment by Kyle2142** [comment]
@weibeld
You can copy them, but only one will receive updates from Telegram.
You need a completely new session (up to 10 max) to receive updates separately

**Comment by weibeld** [comment]
@Kyle2142 thanks!

In my tests it's currently like this: if I have two clients listening on the same chat, then only one of them receives the NewMessage events of this chat. But if I have multiple clients listening on a different chat each, then all of them receive the NewMessage events of their respective chats.

Is this what you mean by only one of them receiving Telegram updates?

And for creating a completely new session, there's no way around the login procedure?

**Comment by Kyle2142** [comment]
Interesting. I haven't used it like that, so I wouldn't know.

Regarding new sessions, it's only a new session because it was a new login.

If you find a way around logging in, you've essentially broken Telegram :)

To discuss this further, I would suggest t.me/telethonchat or
t.me/telethonofftopic

**Comment by Lonami** [comment]
@weibeld just make sure a single client is using a single session file and it will be fine. Copying the authorization key should be fine.

**Comment by weibeld** [comment]
@Lonami great, that helps me, and it solves my use case!
@Kyle2142 ok, good to know about these Telethon chats.

**Comment by weibeld** [comment]
I have to correct what I wrote in the first paragraph of [above comment](https://github.com/LonamiWebs/Telethon/issues/754#issuecomment-402990656).

This turned out to be not true. If running multiple clients on copies of logged-in session files, then (usually) only one client receives the NewMessage updates from Telegram. It seems to be pretty random which client receives the updates, i.e. it may be client A for a while, and then it's client B, etc.

Furthermore, sometimes more than one client receives the updates for a short amount of time (e.g. a NewMessage update for the same message received by three clients simultaneously, and then the next NewMessage update is received by only one client again). The only thing that seems to be guaranteed, I guess, is that *at least* one client receives the updates.

**Comment by Kyle2142** [comment]
Telegram generally sends updates to the "last active" instance of a
session. This means that if an instance sends a message or something, it's
regarded as active.
Either way, you should be using multiple sessions or re-think your approach

**Comment by weibeld** [comment]
Yes, I already changed it to a single TelegramClient that receivds all the updates, and then the filtering is done after that.

On another note: what do you mean by max. 10 sessions? A user can have at most 10 sessions, that is, basically at most 10 Telegram client apps running at the same time? Is this a restriction imposed by Telegram?

**Comment by Lonami** [comment]
@weibeld https://core.telegram.org/api/updates#subscribing-to-updates.
