### ISSUE TITLE
Configure Telethon to use Crawlera Proxy

### ISSUE THREAD

**Issue by ZombieTheBest** [LonamiWebs/Telethon#770]
Hello, 
I just bought a monthly subscription to crawlera and i'm trying to implement it on my script. 
According to crawlera API docs it's necessary to specify an URL.

`curl -vx proxy.crawlera.com:8010 -U <API key>: http://httpbin.org/ip`

I've tried to add the proxy on Telegram Client, but it's not working, giving me:

`Error connecting to HTTP proxy http://<API key>:@proxy.crawlera.com:8010: [Errno -2] Name or service not known`

I've tried to search online, but coudn't find anything about this, just an example using requests.
Thanks for your help

**Comment by Lonami** [comment]
> Saw that PySocks does not support HTTP Proxy Authentication.

Oh, I didn't know that.

> How can I use another proxy library with telethon?

It wasn't me who added the support for proxies to the library, it was done in #37 although it doesn't seem too complicated. You would have to add code similar to the code introduced in said pull request with another library that *does* support HTTP authentication, but I don't know of any since I don't work with proxies at all.

If you were to add support for different libraries, of course I would merge your work. You can also replace `pysocks` with another library and I'll make the necessary changes so both `pysocks` and your changes could coexist.

**Comment by ZombieTheBest** [comment]
@Lonami Thanks for the answer and for pointing me out the commit (now I know where I have to change things!) :)

According to [this](https://support.scrapinghub.com/support/solutions/articles/22000203567-using-crawlera-with-python-requests) example here is using a simple request. 
But [here](https://stackoverflow.com/questions/44239822/urllib-request-urlopenurl-with-authentication) I also see urllib. 

Will take a look into it this evening, 
thanks!

**Comment by Lonami** [comment]
Telegram does offer an HTTP mode, but is not implemented. #112 is tracking that issue.

**Comment by cher-nov** [comment]
@ZombieTheBest,

> So, as I read there, the only way to implement Crawlera would add HTTP mode support, as in TCP i would not be able to "see" the server that the "super-proxy" gave me

AFAIK, yes.

**Comment by Lonami** [comment]
Closing since #477 was closed too. Please report if the mentioned comment there works.
