### ISSUE TITLE
Separate the vector constructor and Vector type in parser

### ISSUE THREAD

**Issue by codefuhrer** [LonamiWebs/Telethon#81]
Most of the TL definitions use the `Vector t` type, but some of them (only one at the moment), use a `vector` constructor.

__Example:__
```cpp
// vector consructor:
future_salts#ae500895 req_msg_id:long now:int salts:vector<future_salt> = FutureSalts;

// Vector type:
messageActionChatCreate#a6638b9a title:string users:Vector<int> = MessageAction;
```
__Problem:__
Currently all vector arguments are being serialized as `Vector` (with uppercase V), so it is impossible to check the CRC32 of the string:

```php
hash('crc32b', 'future_salts req_msg_id:long now:int salts:Vector future_salt = FutureSalts')
=> "94e2d547"

hash('crc32b', 'future_salts req_msg_id:long now:int salts:vector future_salt = FutureSalts')
=> "ae500895" # Passes!
```
It's not a crucial issue, but anyway :no_mouth:

**Comment by Lonami** [comment]
> It's not a crucial issue

Maybe you just pinpointed something more important, though. Notice, the only definitions using **v**ector are, as you said, [`future_salts`](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/Resources/scheme.tl#L93), but **also** [`msg_container`](https://github.com/telegramdesktop/tdesktop/blob/dev/Telegram/Resources/scheme.tl#L103). What's so special about the later? That you [don't read](https://github.com/LonamiWebs/Telethon/blob/048bc81b74471796a7ba3111ddbe04035a0ddd05/telethon/network/mtproto_sender.py#L290) the vector code (only the `handle_container` code itself). So maybe Telegram does a distinction indeed (and since these two are so "special", maybe they just stopped updating the `.tl` to reflect it because it's commented anyway, or maybe they mention it (but then why another type for the vector?)).

I was going to try to invoke [`GetFutureSaltsRequest`](https://lonamiwebs.github.io/Telethon/methods/get_future_salts.html), but I don't know what that `num` parameter is. Perhaps when Telegram server sent it, as shown [here](https://github.com/sochix/TLSharp/blob/ca6e18b50ea7cab777ae0a49e1a7097dc1ae2583/TLSharp.Core/Network/MtProtoSender.cs#L186-L188).

**Comment by codefuhrer** [comment]
> I was going to try to invoke GetFutureSaltsRequest, but I don't know what that num parameter is.

The client may at any time request from the server several (between 1 and 64) future server salts together with their validity periods. Having stored them in persistent memory, the client may use them to send messages in the future even if he changes sessions (a server salt is attached to the authorization key rather than being session-specific). [From docs](https://core.telegram.org/mtproto/service_messages#request-for-several-future-salts)

**Comment by kesor** [comment]
This is in fact not a typo. Just like `msg_container`, the `future_salts` response is using the bare type of the vector instead of the boxed type. This means that there is no `Vector` signature before the vector content, and the `future_salt` is also lower case (bare type, not boxed). So there is no `future_salt` signature before each salt.

`Vector<FutureSalt>` would be this:

    <VectorID><number of salts><FutureSaltID><salt><FutureSaltID><salt> ...

while `vector<future_salt>` is this:

    <number of salts><salt><salt> ...

Big difference, and the response from the server is just like the TL, the second version.

**Comment by Lonami** [comment]
Thanks for pointing that out @kesor, turns out the future salts response is somewhat special and if a user were to make such request, the "response" would never arrive :)

While I'm yet to actually handle those, this should fix that.
