### ISSUE TITLE
Sometimes when a update is sent I get this ..

### ISSUE THREAD

**Issue by Jinqad** [LonamiWebs/Telethon#847]
06-13 13:16 telethon.telegram_client INFO     File lives in another DC
06-13 13:16 telethon.telegram_bare_client INFO     Exporting authorization for data center DcOption(id=5, ip_address='91.108.56.110', port=443, ipv6=False, media_only=False, tcpo_only=False, cdn=False, static=True, secret=None)
06-13 13:16 telethon.telegram_bare_client INFO     Creating exported new client
06-13 13:16 telethon.telegram_bare_client INFO     Connecting to 91.108.56.110:443...
06-13 13:16 telethon.telegram_bare_client INFO     Connection success!
06-13 13:16 telethon.telegram_bare_client INFO     Need to generate new auth key before invoking
06-13 13:16 telethon.telegram_bare_client INFO     Initializing a new connection while invoking
06-13 13:16 telethon.telegram_bare_client INFO     Disconnecting...
Not sure what it really means also sometimes messages are delayed once emitted in the update handler i'm unclear about; usually it can range from 1 min delay to 1 hour and it will disconnect intermittently

**Comment by Lonami** [comment]
That's not when "an update is sent". That's when you are going to download a file that is not in your main data center (Telegram servers are distributed accross several of them). The library sometimes needs to create an authorization key (which is a bit expensive) to download the file you requested.

> messages are delayed once emitted in the update handler i'm unclear about.

This is due to the mentioned process + download of the file, creation of the connection, etc.

**Comment by Jinqad** [comment]
Hmm do you know what i could do to stop the delays and it disconnnecting?

**Comment by Lonami** [comment]
Not downloading the file would definitely avoid the delay.
