### ISSUE TITLE
too few update

### ISSUE THREAD

**Issue by parazitt** [LonamiWebs/Telethon#86]
hello again,
i have  this code:
` tg.add_update_handler(InteractiveTelegramClient.update_handler)`

and in the update_handler i have:
`       global count
        count +=1
        print(count)`

when i run it the output is:

> 1
> 2
> 3
> 4
> 5
> 6
> 7
> 8
> 9
> 10
> 12

while i sent more than 20 massage and not continued any more.
in fack my question is: how i can mange all update from channels, supergroups, groups and users realtime?

**Comment by Lonami** [comment]
> > 10
> > 12

Not sure how that skipped from 10 to 12 in the first place.

> how i can mange all update from channels, supergroups

I mentioned this a few times, channels are different and I would say the don't receive "real time updates" unless you're mentioned in them, or someone pins a message, or someone replies to your messages. The best you can do is check for the messages every so often, as far as I know. If there's a better way, please let me know. Notice that although I made Telethon and it can work with Telegram's API, I'm not an expert in the API itself. I have as much information as you do.

> groups and users

Make sure you have the group/user notifications enabled for these, otherwise I don't think Telegram bothers sending you updates for them.

Last but not least, in theory, Telegram has to send you *all* the updates. I'm not aware if there's some special handling in which you have to do it manually, but you probably would like to give a shot to [`GetDifferenceRequest`](https://lonamiwebs.github.io/Telethon/methods/updates/get_difference.html) and [`GetChannelDifferenceRequest`](https://lonamiwebs.github.io/Telethon/methods/updates/get_channel_difference.html).

**Comment by parazitt** [comment]
hi tank you very much
i removed 11 mistakenly.
i known what you say about  channels.
i need more time to known/say some things.

**Comment by Lonami** [comment]
Any update on this @parazitt? It would be nice if you could try with the again **upstream** and not the `pip` version.

**Comment by parazitt** [comment]
what do you means about **upstream**?

**Comment by Lonami** [comment]
By upstream I mean the code currently available on this repository and *not* the `pip` version. There are instructions on the `README.rst` so you shouldn't have much trouble. Once you've followed the steps, copy the `telethon` folder to wherever your code is so when you `import` from it, it uses that version (the one you cloned) instead `pip`'s.

**Comment by nyuszika7h** [comment]
I know this is a pretty old issue, but just for reference, you can install the latest git version using `pip` without even having git installe:

```https://github.com/LonamiWebs/Telethon/zipball/master

**Comment by Lonami** [comment]
> I know this is a pretty old issue

It's not that old but any useful comments are welcome :)

> ```
> /zipball/master
> ```

TIL, thank you. About the git+ bit too. Perhaps we should add it to the `README.md` and all.

**Comment by Lonami** [comment]
Closing in favor of #237.
