### ISSUE TITLE
Can not connect to Telegram 

### ISSUE THREAD

**Issue by CL545740896** [LonamiWebs/Telethon#979]
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.51:443...
DEBUG:telethon.network.mtprotosender:Connection attempt 1...
DEBUG:telethon.network.mtprotosender:Connection success!
DEBUG:telethon.network.mtprotosender:Starting send loop
DEBUG:telethon.network.mtprotosender:Starting receive loop
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
INFO:telethon.network.mtprotosender:Connection to 149.154.167.51 complete!
INFO:telethon.network.mtprotosender:Connection reset while receiving 
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) InvokeWithLayerRequest...
DEBUG:telethon.network.mtprotosender:Sending 136 bytes...
INFO:telethon.network.mtprotosender:Connection reset while sending 
DEBUG:telethon.network.mtprotosender:Awaiting for the send loop before reconnecting...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6596435110233824320 sent!
DEBUG:telethon.network.mtprotosender:Awaiting for the receive loop before reconnecting...
DEBUG:telethon.network.mtprotosender:Awaiting for the send loop before reconnecting...
DEBUG:telethon.network.mtprotosender:Awaiting for the receive loop before reconnecting...
DEBUG:telethon.network.mtprotosender:Closing current connection...
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.51:443...
DEBUG:telethon.network.mtprotosender:Connection attempt 1...
DEBUG:telethon.network.mtprotosender:Closing current connection...
WARNING:telethon.network.mtprotosender:Attempt 1 at connecting failed: ConnectionResetError: 
DEBUG:telethon.network.mtprotosender:Connection attempt 2...
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.51:443...
DEBUG:telethon.network.mtprotosender:Connection attempt 1...
DEBUG:telethon.network.mtprotosender:Connection success!
DEBUG:telethon.network.mtprotosender:Starting send loop
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) GetStateRequest...
DEBUG:telethon.network.mtprotosender:Sending 104 bytes...
DEBUG:telethon.network.mtprotosender:Starting receive loop
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
INFO:telethon.network.mtprotosender:Connection to 149.154.167.51 complete!
INFO:telethon.client.updates:Asking for the current state after reconnect...
DEBUG:telethon.network.mtprotosender:Connection success!
DEBUG:telethon.network.mtprotosender:Starting send loop
DEBUG:telethon.network.mtprotosender:Outgoing messages 6596435110241824696 sent!
DEBUG:telethon.network.mtprotosender:Packing 3 outgoing message(s) InvokeWithLayerRequest, GetStateRequest, GetStateRequest...
DEBUG:telethon.network.mtprotosender:Sending 200 bytes...
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) MessageContainer...
DEBUG:telethon.network.mtprotosender:Sending 104 bytes...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6596435110233824320, 6596435110241824696, 6596435140136187516 sent!
DEBUG:telethon.network.mtprotosender:Starting receive loop
INFO:telethon.network.mtprotosender:Connection reset while receiving 
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
INFO:telethon.network.mtprotosender:Connection reset while sending 
DEBUG:telethon.network.mtprotosender:Awaiting for the send loop before reconnecting...
INFO:telethon.network.mtprotosender:Connection to 149.154.167.51 complete!
DEBUG:telethon.network.mtprotosender:Awaiting for the send loop before reconnecting...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6596435140128187144 sent!
INFO:telethon.network.mtprotosender:Connection reset while receiving 
INFO:telethon.client.updates:Asking for the current state after reconnect...
DEBUG:telethon.network.mtprotosender:Awaiting for the receive loop before reconnecting...
DEBUG:telethon.network.mtprotosender:Awaiting for the receive loop before reconnecting...
DEBUG:telethon.network.mtprotosender:Awaiting for the send loop before reconnecting...
DEBUG:telethon.network.mtprotosender:Closing current connection...
DEBUG:telethon.network.mtprotosender:Closing current connection...
DEBUG:telethon.network.mtprotosender:Awaiting for the receive loop before reconnecting...
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.51:443...
DEBUG:telethon.network.mtprotosender:Closing current connection...
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.51:443...
DEBUG:telethon.network.mtprotosender:Connection attempt 1...
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.51:443...
DEBUG:telethon.network.mtprotosender:Connection attempt 1...
DEBUG:telethon.network.mtprotosender:Connection attempt 1...
DEBUG:telethon.network.mtprotosender:Connection success!
DEBUG:telethon.network.mtprotosender:Starting send loop
DEBUG:telethon.network.mtprotosender:Packing 4 outgoing message(s) InvokeWithLayerRequest, GetStateRequest, GetStateRequest, GetStateRequest...
DEBUG:telethon.network.mtprotosender:Sending 216 bytes...
DEBUG:telethon.network.mtprotosender:Starting receive loop
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6596435110233824320, 6596435110241824696, 6596435140136187516, 6596435140164190256 sent!
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) MessageContainer...
DEBUG:telethon.network.mtprotosender:Sending 200 bytes...
INFO:telethon.network.mtprotosender:Connection to 149.154.167.51 complete!
DEBUG:telethon.network.mtprotosender:Outgoing messages 6596435140144188844 sent!
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) MessageContainer...
DEBUG:telethon.network.mtprotosender:Sending 104 bytes...
INFO:telethon.client.updates:Asking for the current state after reconnect...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6596435140128187144 sent!
DEBUG:telethon.network.mtprotosender:Packing 5 outgoing message(s) InvokeWithLayerRequest, GetStateRequest, GetStateRequest, GetStateRequest, GetStateRequest...
DEBUG:telethon.network.mtprotosender:Sending 232 bytes...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6596435110233824320, 6596435110241824696, 6596435140136187516, 6596435140164190256, 6596435144363380996 sent!
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) MessageContainer...
DEBUG:telethon.network.mtprotosender:Sending 216 bytes...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6596435144343378628 sent!
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) MessageContainer...
DEBUG:telethon.network.mtprotosender:Sending 104 bytes...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6596435140128187144 sent!
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) MessageContainer...
DEBUG:telethon.network.mtprotosender:Sending 200 bytes...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6596435140144188844 sent!
INFO:telethon.network.mtprotosender:Connection reset while receiving 
DEBUG:telethon.network.mtprotosender:Awaiting for the send loop before reconnecting...
DEBUG:telethon.network.mtprotosender:Awaiting for the receive loop before reconnecting...
DEBUG:telethon.network.mtprotosender:Closing current connection...
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.51:443...
DEBUG:telethon.network.mtprotosender:Connection attempt 1...
DEBUG:telethon.network.mtprotosender:Connection success!
DEBUG:telethon.network.mtprotosender:Starting send loop
DEBUG:telethon.network.mtprotosender:Starting receive loop
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
INFO:telethon.network.mtprotosender:Connection to 149.154.167.51 complete!
DEBUG:telethon.network.mtprotosender:Packing 5 outgoing message(s) InvokeWithLayerRequest, GetStateRequest, GetStateRequest, GetStateRequest, GetStateRequest...
INFO:telethon.client.updates:Asking for the current state after reconnect...
DEBUG:telethon.network.mtprotosender:Sending 232 bytes...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6596435110233824320, 6596435110241824696, 6596435140136187516, 6596435140164190256, 6596435144363380996 sent!
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) MessageContainer...
DEBUG:telethon.network.mtprotosender:Sending 200 bytes...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6596435140144188844 sent!
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) MessageContainer...
DEBUG:telethon.network.mtprotosender:Sending 216 bytes...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6596435144343378628 sent!
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) MessageContainer...
DEBUG:telethon.network.mtprotosender:Sending 232 bytes...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6596435144367380704 sent!
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) MessageContainer...
DEBUG:telethon.network.mtprotosender:Sending 104 bytes...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6596435140128187144 sent!
DEBUG:telethon.network.mtprotosender:Packing 1 outgoing message(s) GetStateRequest...
DEBUG:telethon.network.mtprotosender:Sending 72 bytes...
DEBUG:telethon.network.mtprotosender:Outgoing messages 6596435148626574724 sent!
INFO:telethon.network.mtprotosender:Connection reset while receiving 
DEBUG:telethon.network.mtprotosender:Awaiting for the send loop before reconnecting...
DEBUG:telethon.network.mtprotosender:Awaiting for the receive loop before reconnecting...
DEBUG:telethon.network.mtprotosender:Closing current connection...
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.51:443...
DEBUG:telethon.network.mtprotosender:Connection attempt 1...
DEBUG:telethon.network.mtprotosender:Connection success!
DEBUG:telethon.network.mtprotosender:Starting send loop
DEBUG:telethon.network.mtprotosender:Starting receive loop
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
INFO:telethon.network.mtprotosender:Connection to 149.154.167.51 complete!
DEBUG:telethon.network.mtprotosender:Packing 5 outgoing message(s) InvokeWithLayerRequest, GetStateRequest, GetStateRequest, GetStateRequest, GetStateRequest...
DEBUG:telethon.network.mtprotosender:Sending 232 bytes...
INFO:telethon.client.updates:Asking for the current state after reconnect...
WARNING:telethon.network.mtprotosender:Attempt 1 at connecting failed: timeout: timed out
DEBUG:telethon.network.mtprotosender:Connection attempt 2...
WARNING:telethon.network.mtprotosender:Attempt 2 at connecting failed: OSError: [WinError 10022] 提供了一个无效的参数。

**Comment by CL545740896** [comment]
from telethon import TelegramClient, sync
import os
import logging
logging.basicConfig(level=logging.DEBUG)
os.environ['http_proxy']='http://127.0.0.1:1080'
os.environ['https_proxy']='https://127.0.0.1:1080'
# Use your own values here
api_id = xxxxxx
api_hash = 'xxxxx'

client = TelegramClient('Eric', api_id, api_hash).start()
me = client.get_me()
print(me.stringify())

This is my simply code

**Comment by CL545740896** [comment]
Now ,I can connect to the Telegram ,But ,The second times ,I reconnect it , My account will be banned forever......     
The used phone number has been banned from Telegram and cannot be used anymore

**Comment by Lonami** [comment]
> My account will be banned forever

No, you can contact support to recover it. #824.

**Comment by FARSWINPASARDAM** [comment]
C:\Users\Administrator\Desktop\RESRVE\after_reserved>teleg_test.exe
DEBUG:asyncio:Using proactor: IocpProactor
DEBUG:asyncio:Using proactor: IocpProactor
INFO:telethon.network.mtprotosender:Connecting to 149.154.167.51:443/TcpFull...
DEBUG:telethon.network.mtprotosender:Connection attempt 1...
DEBUG:telethon.network.mtprotosender:Connection success!
DEBUG:telethon.network.mtprotosender:New auth_key attempt 1...
DEBUG:telethon.network.mtprotosender:auth_key generation success!
DEBUG:telethon.network.mtprotosender:Starting send loop
DEBUG:telethon.network.mtprotosender:Starting receive loop
INFO:telethon.network.mtprotosender:Connection to 149.154.167.51:443/TcpFull complete!
ERROR:telethon.network.mtprotosender:Request caused struct.error: argument out of range: InvokeWithLayerRequest(layer=181, query=InitConnectionRequest(api_id=7177417457, device_model='PC 64bit', system_version='10', app_version='1.36.0', system_lang_code='en', lang_pack='', lang_code='en', query=GetConfigRequest(), proxy=None, params=None))
DEBUG:telethon.network.mtprotosender:Waiting for messages to send...
DEBUG:telethon.network.mtprotosender:Receiving items from the network...
Traceback (most recent call last):
  File "teleg_test.py", line 28, in <module>
  File "asyncio\runners.py", line 190, in run
  File "asyncio\runners.py", line 118, in run
  File "asyncio\base_events.py", line 654, in run_until_complete
  File "teleg_test.py", line 23, in main
  File "telethon\client\auth.py", line 135, in _start
  File "telethon\client\telegrambaseclient.py", line 596, in connect
  File "telethon\network\mtprotosender.py", line 183, in send
  File "telethon\network\requeststate.py", line 17, in __init__
  File "telethon\tl\tlobject.py", line 194, in __bytes__
  File "telethon\tl\functions\__init__.py", line 357, in _bytes
  File "telethon\tl\functions\__init__.py", line 127, in _bytes
struct.error: argument out of range
[8576] Failed to execute script 'teleg_test' due to unhandled exception!

when i use it on my pc  with vpn it dont even connenct above log is in vps on germany
i change handler in few ways 
and dont tell thats about api s they work now with telegram lib for sending massages and can fetch massages from my channle and groups that my bot are admin in them but when i want to get masages in other public channles and groups it make this issue even telegram public channle
the code is 
from telethon import TelegramClient, events
import asyncio
import logging
import multiprocessing

logging.basicConfig(level=logging.DEBUG)

# Use your own values here
api_id = '...'
api_hash = '...'
bot_token = '...:...'

client = TelegramClient('bot', api_id, api_hash)

@client.on(events.NewMessage(chats='@BinanceWhaleVolumeAlerts'))  # Replace with the actual channel username
# async def handler(event):
#     print(event.sender_id, event.message.text)
client.
async def handler(event):
    sender = await event.get_sender()
    sender_id = sender.id if sender else None
    message_text = event.message.message
    print(f"Sender ID: {sender_id}, Message: {message_text}")

async def main():
    await client.start(bot_token=bot_token)
    await client.run_until_disconnected()

if __name__ == "__main__":
    multiprocessing.freeze_support()
    asyncio.run(main())

i reviw chats about this issue i saw there is no sense answers for this issue just none sence answersand this rare in libs actually telegram havnt good support for the real solid lib for apis i had never comment on git before just sometimes use for for find solutions but noww ...
can any body solve this ?
